-- Column documentation restored from project_plan5b.sql

COMMENT ON COLUMN "Stakeholder"."Stakeholder_Category" IS 'Owner / Employee / Customer / Supplier / Bank / Government / Accountant / Child Successor / Auditor / Insurance Company';
COMMENT ON COLUMN "Stakeholder"."Stakeholder_Role" IS 'Customer Supplier Employee Owner Creditor Debtor Government SACCO Bank';
COMMENT ON COLUMN "Stakeholder"."Relationship_to_owner" IS 'Son Daughter Niece Uncle Supplier Bank Tenant';
COMMENT ON COLUMN "Stakeholder"."Relationship_Status" IS 'ACTIVE / DECEASED / ESTRANGED / DORMANT / DISPUTED — critical for business continuity';
COMMENT ON COLUMN "Product"."Product_type" IS 'Asset Capital Goods Services';
COMMENT ON COLUMN "Product"."Product_Reorder_Level" IS 'Quantity threshold that triggers a restock alert';
COMMENT ON COLUMN "Product"."Product_Expiry_Tracking" IS '1 = track expiry dates for this product';
COMMENT ON COLUMN "Product"."Is_Asset" IS '1 = this product is a fixed asset (triggers IAS 16 rules)';
COMMENT ON COLUMN "Product"."Is_Service" IS '1 = this product is a service (triggers IFRS 15 rules)';
COMMENT ON COLUMN "ProcessActions"."Process_name" IS 'Purchase Sale Return Inventory Count Payroll Loan Asset Purchase Repair Tax Payment';
COMMENT ON COLUMN "ProcessActions"."Action_Type" IS 'What kind of action this is: STATE_TRANSITION = moves a resource/instrument from one state to another (AVAILABLE->RESERVED, ORDERED->RECEIVED, ACTIVE->PAID) ACCOUNTING_EVENT = posts a Journal entry (sale, depreciation, loan repayment) CONTROL_EVENT = produces evidence or a count without state change (Inventory Count: AVAILABLE->AVAILABLE, but generates STOCK_COUNT record) EVIDENCE_EVENT = attaches a document to an existing event (upload receipt, sign contract) SCHEDULED_EVENT = time-triggered regardless of state (monthly depreciation, annual service) NOTE: From_State and To_State may be NULL for ACCOUNTING_EVENT, CONTROL_EVENT, and EVIDENCE_EVENT types where no state change occurs.';
COMMENT ON COLUMN "ProcessActions"."Cycle_type" IS 'REVENUE/EXPENSE/INVENTORY/LOAN/RENT/ PAYROLL/ASSET/FARMING/INSURANCE/INVESTMENT/INHERITANCE';
COMMENT ON COLUMN "ProcessActions"."Sequence_No" IS 'Order of this action within its cycle template';
COMMENT ON COLUMN "ProcessActions"."Accounting_Event" IS '1 if this stage posts to Journal';
COMMENT ON COLUMN "ProcessActions"."Operational_Event" IS '1 if this stage changes physical/operational state';
COMMENT ON COLUMN "ProcessActions"."From_State" IS 'The state a resource/instrument must be in before this action is valid e.g. AVAILABLE, RESERVED, ORDERED, RECEIVED, ACTIVE, OVERDUE';
COMMENT ON COLUMN "ProcessActions"."To_State" IS 'The state the resource/instrument moves to after this action completes e.g. RESERVED, SOLD, DELIVERED, CLOSED, PAID';
COMMENT ON COLUMN "ProcessActions"."Applies_To" IS 'Which table this state transition applies to: RESOURCES / MONEY / PAYMENT / DOCUMENTS / CYCLE';
COMMENT ON COLUMN "ProcessActions"."Affects_Cash" IS '1 = this action changes a cash or bank balance';
COMMENT ON COLUMN "ProcessActions"."Affects_Resources" IS '1 = this action changes Resources quantity (stock in/out)';
COMMENT ON COLUMN "ProcessActions"."Requires_Approval" IS '1 = this action requires Management approval before proceeding';
COMMENT ON COLUMN "ProcessActions"."Approval_Level" IS 'Approval hierarchy (each level implies all levels below it have been cleared): NONE → OWNER → ACCOUNTANT → AUDITOR → BANK → LAWYER → COURT COURT required for: inheritance disputes, contested assets, fraud investigations';
COMMENT ON COLUMN "ProcessActions"."Process_Description" IS 'Plain language description of what this action does';
COMMENT ON COLUMN "ProcessActions"."Default_Journal_Template" IS 'Reference name for a multi-line posting pattern, NOT a single debit/credit pair. Examples: DR_CASH_CR_INCOME / DR_COGS_CR_INVENTORY / ASSET_DISPOSAL_TEMPLATE. The application layer expands this name into the full set of Journal rows required. A complex event like asset disposal may expand to 4 Journal rows: DR Cash / DR Accum.Depreciation / CR Asset Cost / CR Gain on Disposal. Never assume every event has exactly one debit and one credit.'',';
COMMENT ON COLUMN "ProcessActions"."Evidence_Event" IS '1 if this stage collects, creates, or upgrades evidence. Completes the three-flag classification model: Accounting=1 Operational=1 Evidence=1: Receive Stock (journal + state change + receipt) Accounting=0 Operational=1 Evidence=1: Daily Inventory Count (count only) Accounting=0 Operational=0 Evidence=1: Upload receipt to existing transaction Accounting=1 Operational=0 Evidence=0: Monthly depreciation (journal only)';
COMMENT ON COLUMN "ProcessActions"."Reversal_Method" IS 'How this action can be undone if recorded in error: DIRECT_REVERSAL = simply undo the entry (cash transfer between accounts) REVERSING_ENTRY = post an equal and opposite journal entry (accruals at period start) CORRECTION_ENTRY = post a correcting entry in the current open period (Correction_of FK) RESTATEMENT = formal restatement required (closed-period material error, IAS 8) NOT_REVERSIBLE = cannot be undone once the physical event occurred (sold goods, wages)';
COMMENT ON COLUMN "ProcessActions"."Required_Evidence" IS 'Minimum evidence level: NONE / MEMORY / NOTEBOOK / RECEIPT / BANK / OFFICIAL';
COMMENT ON COLUMN "ProcessActions"."Scheduled_date" IS 'When this action is planned to occur (before it becomes a transaction). Planting: 2026-03-01. Vaccination: 2026-04-15. Loan repayment: 2026-05-02. NULL = not a scheduled action (reactive/event-driven only).';
COMMENT ON COLUMN "ProcessActions"."Is_Recurring" IS '1 = this action recurs on a schedule (monthly payroll, daily milk bottling, weekly egg purchase, quarterly dividend, annual vehicle service)';
COMMENT ON COLUMN "ProcessActions"."Recurrence_Pattern" IS 'DAILY / WEEKLY / MONTHLY / QUARTERLY / SEASONAL / ANNUAL';
COMMENT ON COLUMN "LogicConditions"."When_Event" IS 'VEHICLE_SALE / ASSET_DISPOSAL / LOAN_APPLICATION / SUCCESSION_EVENT / STOCK_COUNT If NULL, the rule evaluates on every transaction matching the Check_Expression';
COMMENT ON COLUMN "LogicConditions"."Then_Actions" IS 'Ordered actions when condition is TRUE, pipe-separated: Example for vehicle sale: BLOCK_TRANSACTION| ALERT_ACCOUNTANT|GENERATE_DISPOSAL_JOURNAL| REQUIRE_EVIDENCE:OFFICIAL|GENERATE_CAPITAL_GAIN_CALC Each action is interpreted by the application layer.';
COMMENT ON COLUMN "LogicConditions"."Else_Actions" IS 'Ordered actions when condition is FALSE, pipe-separated: Example: CONTINUE|GENERATE_RECEIPT|UPDATE_INVENTORY Typically shorter than Then_Actions for routine events.';
COMMENT ON COLUMN "LogicConditions"."Owner_Message" IS 'Message shown to the shop owner when this rule fires. Plain language, local context. Example: This looks like selling a big asset. Please call your accountant first.';
COMMENT ON COLUMN "LogicConditions"."Accountant_Message" IS 'Technical message for the accountant when this rule fires. Different audience from Owner_Message — assumes accounting knowledge. Example: IAS 16 asset disposal: verify book value, calculate gain/loss, remove accumulated depreciation, post disposal journal.';
COMMENT ON COLUMN "LogicConditions"."System_Action" IS 'Machine-readable action code for the application layer. Example: BLOCK|NOTIFY:ACCOUNTANT| GENERATE_JOURNAL:DISPOSAL_TEMPLATE';
COMMENT ON COLUMN "LogicConditions"."Left_Operand" IS 'What is being evaluated e.g. Inventory_Value / Asset_Type / Cycle_stage';
COMMENT ON COLUMN "LogicConditions"."Operator" IS '= / != / > / < / >= / <= / IN / NOT_IN / IS_NULL';
COMMENT ON COLUMN "LogicConditions"."Right_Operand" IS 'The value or threshold being compared against';
COMMENT ON COLUMN "LogicConditions"."Check_Expression" IS 'HUMAN-READABLE rule explanation for documentation only. Machine-readable rule: Left_Operand + Operator + Right_Operand.';
COMMENT ON COLUMN "LogicConditions"."Enforcement" IS 'The rule disposition when evaluated: BLOCK = prevent the action — cannot proceed until resolved INFO = annotate only — event proceeds normally, note is added OVERRIDE = a qualified person (accountant) has reviewed and authorised an exception DEFERRED = the rule is acknowledged but action is permitted pending later resolution NOT_APPLICABLE = this rule does not apply to this business unit, event, or maturity level PASS = the rule was evaluated and the event satisfies all conditions OVERRIDE preserves the original rule while recording that a qualified person made a conscious exception. A rule should never simply disappear because someone bypassed it.';
COMMENT ON COLUMN "LogicConditions"."Review_Level" IS 'NONE → OWNER → SUPERVISOR → ACCOUNTANT → AUDITOR → BANK → LAWYER → COURT — who must approve';
COMMENT ON COLUMN "LogicConditions"."Fact_Type" IS 'ACTUAL / ESTIMATE / ASSUMPTION / PROJECTION — per IFRS reliance on estimates';
COMMENT ON COLUMN "LogicConditions"."Confidence_Level" IS '1=Memory-only 2=Estimate 3=Verbal 4=Written 5=Fully documented';
COMMENT ON COLUMN "LogicConditions"."Logic_Explanation" IS 'Why this rule exists and what it means in plain language';
COMMENT ON COLUMN "LogicConditions"."Failure_Message" IS 'Human-readable message when rule blocks or warns e.g. \"Asset sale requires accountant review\"';
COMMENT ON COLUMN "LogicConditions"."Logic_type" IS 'VALIDATION / CALCULATION / WORKFLOW / REPORTING / DISCLOSURE / AUDIT / COMPLIANCE';
COMMENT ON COLUMN "LogicConditions"."Rule_Result" IS 'The ACTUAL outcome when this rule last fired: PASSED = event satisfied all conditions BLOCKED = event was prevented from proceeding WARNED = event proceeded with a warning logged OVERRIDDEN = rule was overridden by an authorised person (see Rule_Override_by) DEFERRED = event proceeded but resolution is pending NOT_APPLICABLE = rule was not relevant to this event context Stored when the rule fires — allows future query: WHY was this transaction stopped?';
COMMENT ON COLUMN "LogicConditions"."Rule_Reason" IS 'Structured reason code when Rule_Result is BLOCKED, WARNED, or OVERRIDDEN. MISSING_EVIDENCE = required evidence level not met INSUFFICIENT_STOCK = quantity sold exceeds available stock PERIOD_CLOSED = Journal.Period_id references a non-OPEN period ASSET_REQUIRES_REVIEW = fixed asset disposal or disposal requires accountant UNBALANCED_ENTRY = SUM(Debit) != SUM(Credit) DUPLICATE_PAYMENT = same Payment_Method + Payment_Transaction_Reference already exists UNRECONCILED_CASH = Cash_Variance != 0 at period close OPEN_CYCLES = unresolved cycles exist for this period OVERRIDE_AUTHORISED = accountant has authorised an exception to this rule Enables future query: SELECT * FROM LogicConditions WHERE Rule_Reason = PERIOD_CLOSED to find all entries that were blocked due to closed period.';
COMMENT ON COLUMN "LogicConditions"."Rule_Override_by" IS 'Management — who authorised the OVERRIDE. Required when Rule_Result = OVERRIDDEN. Must be ACCOUNTANT or higher access level. Preserves the audit trail: the original rule remains; the override is documented here.';
COMMENT ON COLUMN "LogicConditions"."Rule_Override_date" IS 'When the override was authorised.';
COMMENT ON COLUMN "LogicConditions"."Rule_Override_reason" IS 'Why the override was authorised. Example: Accountant reviewed IAS 16 disposal requirements and confirmed this sale meets all criteria. Override authorised after inspection of the vehicle logbook.';
COMMENT ON COLUMN "Resources"."Resource_type" IS 'INVENTORY / CONSUMABLE / FIXED_ASSET / FINANCIAL_ASSET / NATURAL_RESOURCE / CAPITAL / SERVICE / DIGITAL_ASSET';
COMMENT ON COLUMN "Resources"."Resource_Class" IS 'INVENTORY / FIXED_ASSET / CONSUMABLE / FINANCIAL_ASSET /DIGITAL_CREDIT / BIOLOGICAL_ASSET / SERVICE / LAND / BUILDING / BEARER_PLANT IAS subclass for automatic rule triggering: INVENTORY → IAS 2 (lower of cost and NRV) FIXED_ASSET → IAS 16 (depreciation, disposal rules) CONSUMABLE → IAS 2 (expense on consumption) FINANCIAL_ASSET → IFRS 9 (measurement, impairment) DIGITAL_CREDIT → internal (tokens, prepaid units — expensed on use) BIOLOGICAL_ASSET → IAS 41 (fair value measurement) SERVICE → IFRS 15 (revenue recognition on completion) LAND → IAS 16 (no depreciation) BUILDING → IAS 16 (depreciate over useful life)';
COMMENT ON COLUMN "Resources"."Resource_Category" IS 'PERISHABLE / DURABLE / CONSUMABLE / BIOLOGICAL / DIGITAL / LAND / BUILDING / LIVESTOCK / EQUIPMENT';
COMMENT ON COLUMN "Resources"."Consumption_Method" IS 'to sale, per month, per week';
COMMENT ON COLUMN "Resources"."Fair_Value" IS 'IAS 41: fair value less costs to sell at reporting date';
COMMENT ON COLUMN "Resources"."Fair_Value_Date" IS 'Date of the most recent fair value assessment';
COMMENT ON COLUMN "Resources"."Fair_Value_Basis" IS 'MARKET_PRICE / QUOTED_PRICE / VALUATION_TECHNIQUE / INCOME_APPROACH';
COMMENT ON COLUMN "Resources"."Resources_Status" IS 'AVAILABLE/RESERVED/DAMAGED/EXPIRED/SOLD';
COMMENT ON COLUMN "Resources"."Resources_Source" IS 'PURCHASE/DONATION/INHERITANCE/PRODUCTION';
COMMENT ON COLUMN "Assets"."Asset_Classification" IS 'CURRENT / NON_CURRENT per IAS 1.66';
COMMENT ON COLUMN "Assets"."Cost_Amount" IS 'IAS 16: cost at acquisition. Depreciation base = Cost_Amount - Residual_Value.';
COMMENT ON COLUMN "Assets"."Residual_Value" IS 'IAS 16: estimated amount receivable on disposal at end of useful life.';
COMMENT ON COLUMN "Assets"."Useful_Life_Years" IS 'IAS 16: review annually. Changes applied prospectively.';
COMMENT ON COLUMN "Assets"."Depreciation_Method" IS 'STRAIGHT_LINE / REDUCING_BALANCE / UNITS_OF_PRODUCTION';
COMMENT ON COLUMN "Assets"."Accumulated_Depreciation" IS 'IAS 16.73(d): sum of all depreciation charged since acquisition.';
COMMENT ON COLUMN "Assets"."Accumulated_Impairment" IS 'IAS 36: total impairment losses recognised — separate from depreciation.';
COMMENT ON COLUMN "Assets"."Carrying_Amount" IS 'Derived: Cost_Amount - Accumulated_Depreciation - Accumulated_Impairment.';
COMMENT ON COLUMN "Assets"."Acquisition_Date" IS 'Date the asset was purchased or acquired.';
COMMENT ON COLUMN "Assets"."Placed_In_Service_Date" IS 'IAS 16: date available for use — depreciation starts here.';
COMMENT ON COLUMN "Assets"."Disposal_Date" IS 'Date sold, scrapped, or transferred. Depreciation stops here.';
COMMENT ON COLUMN "Equity"."Equity_type" IS 'Owner Capital / Retained Earnings / Reserves / Drawings';
COMMENT ON COLUMN "Liability"."Liability_Type" IS 'Supplier Credit / Loan / Salary / Tax / Rent / Lease';
COMMENT ON COLUMN "Liability"."Liability_Classification" IS 'CURRENT / NON_CURRENT per IAS 1.69 — required for formal reporting';
COMMENT ON COLUMN "Income"."Transactions_id" IS 'Transactions — primary receipt link. SHORTCUT for single-item transactions only.';
COMMENT ON COLUMN "Income"."Income_type" IS 'sales, rent, dividence';
COMMENT ON COLUMN "Income"."Income_Source" IS 'sales, investments';
COMMENT ON COLUMN "Income"."Income_Category" IS 'OPERATING_REVENUE / RENTAL / INTEREST / DIVIDEND GAIN_ON_DISPOSAL / DONATION / OTHER';
COMMENT ON COLUMN "Income"."Accounting_Nature" IS 'The financial statement classification of this income. Required for Income Statement, Cash Flow, and Balance Sheet to be correctly derived. REVENUE = sales of goods and services in the ordinary course of business (IFRS 15) OTHER_INCOME = income outside ordinary activities (rent, dividends, agricultural sales) FINANCE_INCOME = interest earned on bonds, savings (IFRS 9 EIR method) GAIN = disposal proceeds minus carrying amount (not recurring revenue) FAIR_VALUE_GAIN = IAS 41 biological asset revaluation gain CAPITAL_CONTRIBUTION = owner injecting equity — not income at all, equity movement only Only REVENUE, OTHER_INCOME, FINANCE_INCOME, GAIN flow into the Income Statement. CAPITAL_CONTRIBUTION goes to the Equity Statement only.'',';
COMMENT ON COLUMN "Income"."Business_Unit" IS 'which unit this belongs to: SHOP / FARM / INVESTMENTS / RENTAL / TEACHING';
COMMENT ON COLUMN "Income"."Marketing_Channel" IS 'DIRECT / SACCO_AGRICULTURAL / SACCO_CHURCH / SHOP / BUTCHER / EXPORT / BROKER';
COMMENT ON COLUMN "Income"."Standard_Reference" IS 'IFRS 15 / IAS 18 — which standard governs recognition';
COMMENT ON COLUMN "Income"."Outstanding_Amount" IS 'Net_Amount minus Cash_Received';
COMMENT ON COLUMN "Income"."Period_id" IS 'Structures (Structures_Type=ACCOUNTING_PERIOD). Authoritative period reference — use this for trial balance and financial statement queries. If Journal.Period_id = June and Income.Period_id = July, the Journal wins. Income.Period_id must match Journal.Period_id for the transactions it summarises.';
COMMENT ON COLUMN "Expenditure"."Transactions_id" IS 'where the the transaction cycle began - that opened this expenditure cycle';
COMMENT ON COLUMN "Expenditure"."Expenditure_type" IS 'Expense / Capital / Loan / Investment / Owner_Drawings / Tax / purchachse / utility expense / one-time cost,';
COMMENT ON COLUMN "Expenditure"."Expenditure_subtype" IS 'TOKEN_PURCHASE/RECURRING_BILL/ONE_TIME/PAYROLL/LOAN_REPAYMENT';
COMMENT ON COLUMN "Expenditure"."Is_Prepaid" IS '1=prepaid creates prepaid asset until consumed (electricity token, prepaid water)';
COMMENT ON COLUMN "Expenditure"."Billing_Reference" IS 'Meter number, account number, payroll reference for recurring items';
COMMENT ON COLUMN "Expenditure"."Consumption_Unit" IS '''kWh purchased / litres / tokens / units — quantity of utility acquired';
COMMENT ON COLUMN "Expenditure"."Expenditure_Category" IS 'COGS / INVENTORY_PURCHASE / SALARY / DEPRECIATION / IMPAIRMENT / UTILITIES / TRANSPORT / RENT / LOAN_INTEREST / LOAN_PRINCIPAL / INSURANCE / TAX / MAINTENANCE / OWNER_DRAWING / BAD_DEBT / OTHER';
COMMENT ON COLUMN "Expenditure"."Expenditure_Behaviour" IS 'FIXED/VARIABLE/MIXED';
COMMENT ON COLUMN "Expenditure"."Expenditure_Frequency" IS 'DAILY/WEEKLY/MONTHLY/SEASONAL';
COMMENT ON COLUMN "Expenditure"."Business_Unit" IS 'which unit this belongs to: SHOP / FARM / INVESTMENTS / RENTAL / TEACHING';
COMMENT ON COLUMN "Expenditure"."Expenditure_Outstanding" IS 'Net_Amount minus Expense_Paid';
COMMENT ON COLUMN "Expenditure"."Period_id" IS 'Structures ACCOUNTING_PERIOD. Authoritative period reference.';
COMMENT ON COLUMN "Expenditure"."Is_Capitalizable" IS 'this expenditure can be capitalised as an asset under IAS 16';
COMMENT ON COLUMN "Expenditure"."Accounting_Nature" IS 'Income statement classification: OPERATING_EXPENSE/COGS/FINANCE_COST/TAX go to Income Statement. CAPITAL_ASSET_PURCHASE/LOAN_PRINCIPAL/OWNER_DRAWING/ INVESTMENT_PURCHASE/PREPAYMENT go to Balance Sheet only.';
COMMENT ON COLUMN "Journal"."Correction_of" IS 'Journal — the original entry this row corrects. The original entry is NEVER modified or deleted — it remains permanently visible. A correction is a NEW journal entry that reverses the error and re-states correctly. Example: original DR Expense 10,000 CR Cash 10,000 (wrong amount) -> correction 1: DR Cash 10,000 CR Expense 10,000 (reversal) -> correction 2: DR Expense 8,000 CR Cash 8,000 (correct entry) Both corrections reference Correction_of = original Journal_id.';
COMMENT ON COLUMN "Journal"."Correction_Reason" IS 'Mandatory when Correction_of is set. Plain language explanation of what was wrong and why this correction is needed. Example: Wrong amount entered — milk purchase was KES 8,000 not KES 10,000. Example: Posted to wrong account — should be Utilities not Transport.';
COMMENT ON COLUMN "Journal"."Corrected_By" IS 'Management — who authorised and posted this correction. Cannot be the same person who posted the original entry for high-value corrections. Dual-control: different person posts original vs correction.';
COMMENT ON COLUMN "Journal"."Correction_Date" IS 'The date this correction was authorised. May differ from Transaction_Date (the economic event date) and Posting_Date (entry date). Correction_Date drives the audit trail in Account_History.';
COMMENT ON COLUMN "Journal"."Transaction_Date" IS 'When the economic event occurred (the accounting date). This is the authoritative date for period assignment. A sale on 31 July entered on 2 August has Transaction_Date=2026-07-31. Use Transaction_Date (not Created_at) for trial balance period filtering.';
COMMENT ON COLUMN "Journal"."Posting_Date" IS 'When this entry was entered into the system. May differ from Transaction_Date when entries are recorded after the fact. Created_at records the database timestamp. Posting_Date is the intentional entry date.';
COMMENT ON COLUMN "Journal"."Period_id" IS 'FK to Structures (Structures_Type=ACCOUNTING_PERIOD). The authoritative period this journal entry belongs to. Trial balance query: WHERE Journal.Period_id = :structures_id NOT: WHERE Journal.Created_at BETWEEN :start AND :end Set by the application when posting. Must match an OPEN period.';
COMMENT ON COLUMN "Journal"."Recognition_Basis" IS 'Describes the recognition method of THIS specific journal entry. NOT a flag to generate a parallel cash version of an accrual entry. A single economic event produces one set of journal entries, not two. ACCRUAL = this entry recognises income/expense before cash moves (bond coupon, rent receivable). CASH = this entry records actual cash movement. Cash view is obtained by: JOIN Account WHERE Account_Code IN (1000,1100) — filter cash accounts, not by generating a separate CASH journal row for the same transaction.';
COMMENT ON COLUMN "Reports"."Reports_type" IS 'ACCOUNTING REPORTS: Balance Sheet / Income Statement / Trial Balance / Cash Flow / Equity Statement OPERATIONAL REPORTS: Daily Sales / Inventory Movement / Loan Status / Customer Debt / Supplier Credit / Rent Arrears MANAGEMENT REPORTS: Profit by Product / Profit by Cycle / Cash Forecast / Asset Register COMPLIANCE REPORTS: VAT Return / Tax Filing / Audit Pack SUCCESSION REPORT: Complete business handover document showing current assets, outstanding debts, key suppliers and customers, inventory status, pending cycles, legal documents, knowledge repository, and recommendations for the incoming owner.';
COMMENT ON COLUMN "Reports"."Report_category" IS 'OPERATIONAL — daily business view (Today Sales, Milk Remaining, Eggs in Stock) MANAGEMENT — owner decisions (Profit by Farm, Loan Forecast, Cash Forecast) ACCOUNTING — professional view (Trial Balance, Income Statement, Cash Flow, Balance Sheet) COMPLIANCE — regulatory (VAT Return, Tax Filing, Audit Pack) SUCCESSION — handover document (Assets, Debts, Suppliers, Knowledge, Recommendations)';
COMMENT ON COLUMN "Reports"."CF_Category" IS 'OPERATING / INVESTING / FINANCING — cash flow statement category';
COMMENT ON COLUMN "Reports"."Net_Profit" IS 'Income minus Expenditure = Net Profit';
COMMENT ON COLUMN "Reports"."Report_basis" IS 'CASH or ACCRUAL — which recognition basis this report uses';
COMMENT ON COLUMN "Reports"."Report_Stage" IS 'Position in the accounting close chain: TRIAL_BALANCE_UNADJUSTED = raw Journal totals before period-end adjustments ADJUSTMENTS = the adjusting entries themselves (depreciation, accruals, prepayments) TRIAL_BALANCE_ADJUSTED = Journal totals after all adjusting entries are posted INCOME_STATEMENT = revenue and expense accounts from adjusted trial balance BALANCE_SHEET = asset, liability, equity accounts from adjusted trial balance CASH_FLOW_STATEMENT = derived from journal entries classified by Cash_Flow_Category EQUITY_STATEMENT = changes in owner equity The chain is: TRIAL_BALANCE_UNADJUSTED → ADJUSTMENTS → TRIAL_BALANCE_ADJUSTED → INCOME_STATEMENT + BALANCE_SHEET + CASH_FLOW_STATEMENT Financial statements are produced ONLY from the ADJUSTED trial balance.';
COMMENT ON COLUMN "Reports"."Is_Adjusted" IS '0 = unadjusted trial balance (raw Journal totals) 1 = adjusted trial balance (after depreciation, accruals, prepayments, inventory adjustments) Financial statements must only be derived from Is_Adjusted=1 reports.';
COMMENT ON COLUMN "Reports"."Parent_Report_id" IS 'Reports — links this report to the prior stage. Adjusted TB links to its Unadjusted TB parent. Income Statement links to its Adjusted TB parent. This chain makes the progression auditable: you can always trace a financial statement back through the adjusted TB to the original unadjusted TB and the raw journal.';
COMMENT ON COLUMN "Reports"."Adjustment_count" IS 'Number of adjusting entries posted between the unadjusted and adjusted trial balance. Zero on unadjusted TB. Populated when Is_Adjusted is set to 1.';
COMMENT ON COLUMN "Organisation"."Business_Units" IS 'Comma-separated business units within this enterprise: SHOP / FARM / INVESTMENTS / RENTAL / TEACHING';
COMMENT ON COLUMN "Organisation"."Organisation_Type" IS 'Retail Salon Agrovet Cyber Wholesale Restaurant Transport';
COMMENT ON COLUMN "Organisation"."Worth_Estimated" IS 'Owner/accountant/bank estimate of true market value including goodwill';
COMMENT ON COLUMN "Organisation"."Worth_Book_Value" IS 'Assets − Liabilities = Equity — the book value of the machine today';
COMMENT ON COLUMN "Organisation"."Worth_Method" IS 'BOOK_VALUE / INCOME_MULTIPLE / ASSET_BASED / MARKET / REPLACEMENT_COST';
COMMENT ON COLUMN "Records"."Records_type" IS 'The aggregation level this record represents — must not be mixed: TRANSACTION_BATCH = one customer basket or one purchase event (lines grouped for one receipt) DAILY_SUMMARY = all transaction batches for one business day (feeds weekly report) PERIOD_SUMMARY = all daily summaries for one week or month (feeds trial balance) ACCOUNTING_CLOSE = the closing record for a formal accounting period (trial balance input) INVENTORY_COUNT = physical count result — not a sales batch or summary Rules: Receipt -> TRANSACTION_BATCH Daily Sales Report -> DAILY_SUMMARY Weekly Income/Expenditure -> PERIOD_SUMMARY Trial Balance -> ACCOUNTING_CLOSE Never mix: a TRANSACTION_BATCH is not a DAILY_SUMMARY even if both use Records.'',';
COMMENT ON COLUMN "Records"."Records_date" IS 'Business date this record represents (not when it was created)';
COMMENT ON COLUMN "Records"."Period_start" IS 'Start of the batch window';
COMMENT ON COLUMN "Records"."Period_end" IS 'End of the batch window';
COMMENT ON COLUMN "Records"."Business_Unit" IS 'SHOP / FARM / INVESTMENTS / RENTAL / TEACHING';
COMMENT ON COLUMN "Records"."Total_Income" IS 'Sum of all Income transactions in this batch';
COMMENT ON COLUMN "Records"."Total_Expenditure" IS 'Sum of all Expenditure transactions in this batch';
COMMENT ON COLUMN "Records"."Total_Cash_In" IS 'Cash and mobile money received in this batch';
COMMENT ON COLUMN "Records"."Total_Cash_Out" IS 'Cash and mobile money paid out in this batch';
COMMENT ON COLUMN "Records"."Transaction_Count" IS 'Number of Transactions rows in this batch';
COMMENT ON COLUMN "Records"."Net_Position" IS 'Total_Income minus Total_Expenditure for this period';
COMMENT ON COLUMN "Records"."Structures_id" IS 'Structures ACCOUNTING_PERIOD row — links batch to its named period';
COMMENT ON COLUMN "Records"."Period_id" IS 'to Structures — the specific ACCOUNTING_PERIOD this batch belongs to. For TRANSACTION_BATCH: the daily period. For DAILY_SALES: the weekly period. For MONTHLY_SUMMARY: the monthly period. Authoritative for period-based report queries — use Period_id, not date ranges.';
COMMENT ON COLUMN "Records"."Opening_Cash" IS 'Cash in till at start of this period (counted, not calculated)';
COMMENT ON COLUMN "Records"."Expected_Closing_Cash" IS 'Calculated: Opening_Cash + Total_Cash_In - Total_Cash_Out. Populated automatically at period close by application logic.';
COMMENT ON COLUMN "Records"."Actual_Closing_Cash" IS 'Cash physically counted at end of period. Must be entered by cashier or owner before the period can be marked CLOSED.';
COMMENT ON COLUMN "Records"."Cash_Variance" IS 'Actual_Closing_Cash minus Expected_Closing_Cash. Zero = reconciled. Non-zero triggers LogicConditions WARN rule. Never zero this out silently — every variance must be explained.';
COMMENT ON COLUMN "Records"."Stock_Reconciliation" IS 'Inventory movement per perishable product for this period. Structure: [{product_id, product_name, opening, purchased, sold, spoiled, adjusted, closing}] Control: opening + purchased - sold - spoiled ± adjusted = closing. Any discrepancy triggers investigation. Applies to: milk, eggs, vegetables, fuel, beer, meat.';
COMMENT ON COLUMN "Documents"."Transactions_id" IS 'Transactions — the specific transaction this document records. Primary receipt model: Document → Records → Transactions (use Records_id for multi-line receipts). This column is a shortcut for single-item transactions only.';
COMMENT ON COLUMN "Documents"."Document_type" IS 'INVOICE / RECEIPT / QUOTE / LOAN_AGREEMENT / OWNERSHIP_PROOF / BALANCE_SHEET';
COMMENT ON COLUMN "Documents"."Documents_no" IS 'human-readable · INV-0042 / RCP-0017';
COMMENT ON COLUMN "Documents"."Stakeholder_id" IS 'who this is for / from';
COMMENT ON COLUMN "Documents"."Organisation_id" IS 'Organisation — which business unit issued or received this document. A receipt must identify the specific shop or farm, not just the family name. Enables correct document header: Village Hope Shop, Naivasha vs Chebet Farms. Without this, a receipt cannot distinguish which of Daniel''s businesses issued it.';
COMMENT ON COLUMN "Documents"."Document_Title" IS 'Invoice Quotation Purchase Order Delivery Note Credit Note Debit Note Bank Statement M-Pesa Statement Loan Agreement Asset Register Stock Count Tax Filing Generated Report';
COMMENT ON COLUMN "Documents"."Action" IS 'CREATE / UPDATE / VOID / DELETE';
COMMENT ON COLUMN "Documents"."Device" IS 'device or terminal used';
COMMENT ON COLUMN "Documents"."Document_date" IS 'issue date';
COMMENT ON COLUMN "Documents"."Due_date" IS 'payment due · invoices only';
COMMENT ON COLUMN "Documents"."Gross_amount" IS 'before tax';
COMMENT ON COLUMN "Documents"."Tax_amount" IS 'VAT / levy portion';
COMMENT ON COLUMN "Documents"."Net_Amount" IS 'total payable';
COMMENT ON COLUMN "Documents"."Document_status" IS 'DRAFT / SENT / PAID / VOID / OVERDUE Draft / Submitted / Verified / Approved / Rejected / Archived / Deleted';
COMMENT ON COLUMN "Documents"."Document_Authenticity" IS 'ORIGINAL / CERTIFIED_COPY / PHOTOCOPY / SCANNED / VERBAL_RECORD / RECONSTRUCTED';
COMMENT ON COLUMN "Documents"."Is_Original" IS '1 = this is the original document, not a copy';
COMMENT ON COLUMN "Documents"."Is_Legally_Signed" IS '1 = document bears a wet ink or equivalent legal signature';
COMMENT ON COLUMN "Documents"."Is_Digitally_Signed" IS '''1 = document bears a verified digital signature';
COMMENT ON COLUMN "Documents"."Is_Witnessed" IS '''1 = a third party witnessed the signing of this document';
COMMENT ON COLUMN "Documents"."Expiry_date" IS 'When this document expires — relevant for licences, insurance, loan agreements';
COMMENT ON COLUMN "Documents"."Issued_by" IS 'Institution or person who issued this document (bank, court, government body)';
COMMENT ON COLUMN "Documents"."Custodian" IS 'Stakeholder — who currently holds the physical original';
COMMENT ON COLUMN "Documents"."File_path" IS 'path to generated PDF on disk';
COMMENT ON COLUMN "Documents"."Generated" IS '0=manual · 1=system generated';
COMMENT ON COLUMN "Documents"."Generated_By" IS 'Management — who created or generated this document';
COMMENT ON COLUMN "Documents"."Approved_By" IS 'Management — who approved or signed off on this document. Loan agreements: BANK. Balance sheet: ACCOUNTANT. Receipts: OWNER or SYSTEM.';
COMMENT ON COLUMN "Documents"."Confidence_Level" IS '1=Draft estimate 2=Internal record 3=Signed copy 4=Countersigned 5=Legally registered';
COMMENT ON COLUMN "Documents"."Notes" IS '· payment terms · footer text · instructions';
COMMENT ON COLUMN "Management"."Administration_type" IS 'Owner child Manager Family Cashier User Worker';
COMMENT ON COLUMN "Management"."Inheritance_Status" IS 'CURRENT_OWNER/SUCCESSOR/RETIRED/DECEASED/ADVISOR';
COMMENT ON COLUMN "Management"."Management_Role" IS 'Owner Employee Salesperson Manager Accountant';
COMMENT ON COLUMN "Management"."Management_Cost" IS 'Salary';
COMMENT ON COLUMN "Management"."Arrangement_Type" IS 'SALARY / PROFIT_SHARE / COMMISSION / FAMILY_CONTRIBUTION / OWNER_DRAWINGS / VOLUNTEER';
COMMENT ON COLUMN "Management"."Arrangement_Rate" IS 'Percentage for profit-share or commission arrangements';
COMMENT ON COLUMN "Management"."Access_Level" IS 'What this person can see and do in the system: OWNER_FULL / MANAGER / CASHIER / VIEWER / ACCOUNTANT / ADVISOR';
COMMENT ON COLUMN "Management"."Document_id" IS 'UNIQUE INDEX `uq_doc_number` (`Document_type`, `Documents_no`, `Organisation_id`) COMMENT ''Prevents duplicate document numbers per document type per business unit. Duplicate receipt numbers are a serious accounting integrity problem.';
COMMENT ON COLUMN "Management"."Document_id" IS 'Prevents duplicate document numbers per document type per business unit. Duplicate receipt numbers are a serious accounting integrity problem.';
COMMENT ON COLUMN "Structures"."Parent_Structure_id" IS '(self-reference) — enables Framework → Standard → Section → Rule hierarchy. NULL = top-level Framework node. Non-NULL = child of the referenced Structure.';
COMMENT ON COLUMN "Structures"."Structure_Level" IS 'FRAMEWORK — top level (IFRS, GAAP, IAS, INTERNAL, FAMILY) STANDARD — a named standard under a framework (IAS 16, IFRS 15) SECTION — a section within a standard (Recognition, Measurement, Disclosure) RULE — a specific rule to enforce (Depreciation method, Revenue gate)';
COMMENT ON COLUMN "Structures"."Structures_Type" IS 'Disciplined vocabulary — each type answers a different question: FRAMEWORK = externally authoritative body of rules (IFRS, IAS, GAAP, TAX, IPSAS) STANDARD = a named standard under a framework (IAS 2, IAS 16, IFRS 15, IFRS 9) STANDARD_SECTION = a section within a standard (Recognition, Measurement, Disclosure) ACCOUNTING_POLICY = the business selected application of a standard (FIFO, straight-line) MEASUREMENT_POLICY = how an asset or liability is measured (HISTORICAL_COST, FAIR_VALUE) RECOGNITION_POLICY = when income/expense enters the books (ON_DELIVERY, ON_PAYMENT) DISCLOSURE_POLICY = what must be disclosed and to whom CONTROL_POLICY = internal operating controls (count eggs every Friday) WORKFLOW_POLICY = approval rules and escalation thresholds REPORT_TEMPLATE = layout and content definition for a report type ACCOUNTING_PERIOD = a time period with a lifecycle (OPEN/CLOSED/AUDITED/LOCKED) TAX_RULE = Kenyan or national tax obligation (turnover tax, rental income';
COMMENT ON COLUMN "Structures"."Effective_From" IS 'When this rule takes effect — supports period-specific frameworks';
COMMENT ON COLUMN "Structures"."Effective_To" IS 'When this rule expires (NULL = still active)';
COMMENT ON COLUMN "Structures"."Mandatory" IS '1 = must be satisfied before transaction proceeds';
COMMENT ON COLUMN "Structures"."Compliance_Level" IS 'FULLY_COMPLIANT / PARTIALLY_COMPLIANT / NON_COMPLIANT';
COMMENT ON COLUMN "Structures"."Business_Maturity" IS 'INFORMAL / SEMI_FORMAL / FORMAL / AUDITED / BANKABLE — which stage this rule applies from';
COMMENT ON COLUMN "Structures"."Escalation_Role" IS 'NONE → OWNER → ACCOUNTANT → AUDITOR → BANK → LAWYER → COURT';
COMMENT ON COLUMN "Structures"."Measurement_Basis" IS 'HISTORICAL_COST / FAIR_VALUE / NRV / AMORTIZED_COST / PRESENT_VALUE';
COMMENT ON COLUMN "Structures"."Created_By" IS 'FK to Management — who defined this rule';
COMMENT ON COLUMN "Structures"."Approved_By" IS 'Management — who authorised this rule (accountant, bank officer)';
COMMENT ON COLUMN "Structures"."Framework_Name" IS 'GAAP / IFRS / IAS / IFRS_SME / IPSAS / TAX / INTERNAL_POLICY / FAMILY_RULE / VILLAGE_PRACTICE';
COMMENT ON COLUMN "Structures"."Framework_Version" IS 'e.g. IFRS_SME_2015 / IFRS_2025 / IAS_16 / IAS_2 / IAS_41';
COMMENT ON COLUMN "Structures"."Framework_Priority" IS '1= IAS 2=IFRS 3=National Tax 4=Internal Policy 5=Family Rule — lower number wins conflicts';
COMMENT ON COLUMN "Structures"."Rule_Code" IS 'Short code e.g. IAS16_CAPEX / IFRS15_RECOG / CTRL_STOCKCOUNT';
COMMENT ON COLUMN "Structures"."Standard_Reference" IS 'The specific IAS/IFRS paragraph e.g. IAS 2.9 / IFRS 15.31';
COMMENT ON COLUMN "Structures"."Rule_Severity" IS 'BLOCK=prevent / WARN=flag for accountant / INFO=annotate only';
COMMENT ON COLUMN "Structures"."Applies_To_Table" IS 'Controlled vocabulary — the table this rule governs. Use EXACTLY these values (no aliases, no free text): TRANSACTION = mydb.Transactions RESOURCE = mydb.Resources (inventory, assets, biological assets) MONEY = mydb.Money (loans, bonds, receivables, insurance) PAYMENT = mydb.Payment (M-Pesa, bank, cash settlements) JOURNAL = mydb.Journal (accounting entries) ACCOUNT = mydb.Account (chart of accounts balances) INCOME = mydb.Income (period income snapshot) EXPENDITURE = mydb.Expenditure (period expenditure snapshot) ASSET = mydb.Assets (fixed asset register snapshot) LIABILITY = mydb.Liability (obligation snapshot) EQUITY = mydb.Equity (owner interest snapshot) DOCUMENT = mydb.Documents (evidence registry) REPORT = mydb.Reports (generated reports) MANAGEMENT = mydb.Management (access and approval) RECORD = mydb.Records (batch and period summaries) ANY = applies regardless of table (period close check, balance check)';
COMMENT ON COLUMN "Structures"."Recognition_Method" IS 'Immediate / On Consumption / On Depreciation / On Completion / On Payment / On Invoice';
COMMENT ON COLUMN "Structures"."Period_name" IS 'Human-readable label for this period: Mon 14 Jul 2026 / Week 29 2026 / Jul 2026 / Q3 2026 / FY2026';
COMMENT ON COLUMN "Account_codes"."Code_categories" IS 'ASSET / LIABILITY / EQUITY / INCOME / EXPENDITURE';
COMMENT ON COLUMN "Account_codes"."Standard_Reference" IS 'PRIMARY standard reference for this account code. One account may be governed by several standards over its life. Example: Receivables involves IAS 1 (presentation), IFRS 9 (measurement), IFRS 7 (disclosure). IAS 2=Inventory / IAS 16=PPE / IAS 32=Financial Instruments / IFRS 15=Revenue This field records the primary standard only — not a complete standards mapping.';
COMMENT ON COLUMN "Account_codes"."Statement_Section" IS 'Where this account appears in financial statements: CURRENT_ASSET = cash, receivables, inventory, prepayments (IAS 1.66) NON_CURRENT_ASSET = PPE, investment property, biological assets, bonds (IAS 1.66) CURRENT_LIABILITY = payables, short-term loans, tax payable (IAS 1.69) NON_CURRENT_LIABILITY = long-term loans, deferred tax (IAS 1.69) EQUITY = capital, retained earnings, drawings OPERATING_INCOME = revenue from main business activities (IFRS 15) OTHER_INCOME = rent, dividends, fair value gains (IAS 40, IAS 41, IFRS 9) COGS = cost of inventory sold (IAS 2) -- NOT inventory purchases OPERATING_EXPENSE = wages, utilities, transport, insurance FINANCE_COST = loan interest (IAS 23) TAX = income tax (IAS 12) Enables trial balance, income statement, and balance sheet queries without hardcoding account names or code ranges in application logic.';
COMMENT ON COLUMN "Account_codes"."Is_Active" IS '1 = active in chart of accounts';
COMMENT ON COLUMN "Catalogue"."Catalogue_id" IS 'KNOWLEDGE LAYER: accounting duality engine. Each row is a complete blueprint for one business event. Defines: which accounts to debit/credit, what document to generate, what operational impact occurs, who must approve, what report line is affected. Catalogue is the bridge between a real-world event and its accounting consequences.';
COMMENT ON COLUMN "Catalogue"."Event_Name" IS 'Human-readable event e.g. SELL_EGGS / BUY_STOCK / PAY_LOAN / DISPOSE_ASSET';
COMMENT ON COLUMN "Catalogue"."Event_Description" IS 'Plain language description';
COMMENT ON COLUMN "Catalogue"."Debit_Account_code" IS 'Display-only. Use Debit_Account_fk_id for integrity. Primary account to debit. This is a POSTING TEMPLATE, not a complete accounting engine. Simple events (cash sale): one debit, one credit. Complex events (disposal, VAT sale, loan payment): the application layer adds the full posting to Journal using Catalogue only as a starting template. Example: Cash sale: DR 1000 Cash, CR 4000 Sales Credit sale with VAT: DR 1200 Receivable, CR 4000 Sales, CR 2200 Tax Payable Loan payment: DR 2100 Loan Principal + DR 5200 Interest, CR 1000 Cash';
COMMENT ON COLUMN "Catalogue"."Credit_Account_code" IS 'Display-only. Use Credit_Account_fk_id for integrity.';
COMMENT ON COLUMN "Catalogue"."Secondary_Debit_code" IS 'Display-only. Second debit account for complex events (asset disposal, loan split)';
COMMENT ON COLUMN "Catalogue"."Secondary_Credit_code" IS 'Display-only. Second credit account for complex events (VAT on sales)';
COMMENT ON COLUMN "Catalogue"."Cash_Flow_Category" IS 'Cash flow statement classification — defined at event level, not at report time. OPERATING — milk purchase, wages, utilities, rent received, COGS payment INVESTING — vehicle purchase, bond purchase, asset disposal proceeds FINANCING — loan drawdown, loan repayment principal, owner capital injection, drawings NONE — non-cash events (depreciation, fair value revaluation, accruals) Derive the Report.CF_Category from this field, not from manual classification at reporting.';
COMMENT ON COLUMN "Catalogue"."Operational_Impact" IS 'INVENTORY_DECREASE / INVENTORY_INCREASE / ASSET_TRANSFER / NONE';
COMMENT ON COLUMN "Catalogue"."Risk_Level" IS 'LOW / MEDIUM / HIGH';
COMMENT ON COLUMN "Catalogue"."Documentation_type" IS 'RECEIPT / INVOICE / DELIVERY_NOTE / DISPOSAL_NOTE / LOAN_AGREEMENT / NONE';
COMMENT ON COLUMN "Catalogue"."Report_trigger" IS 'DAILY_SALES / INCOME_STATEMENT / CASH_FLOW / ASSET_REGISTER / LOAN_STATUS';
COMMENT ON COLUMN "Catalogue"."Escalation_Role" IS 'NONE / OWNER / ACCOUNTANT / AUDITOR / LAWYER / BANK';
COMMENT ON COLUMN "Catalogue"."Cycle_type" IS 'Standardised 11-value vocabulary — identical across ProcessActions, Catalogue, Transactions: INCOME / EXPENDITURE / INVENTORY / LOAN / RENT / PAYROLL / ASSET / FARMING / INSURANCE / INVESTMENT / INHERITANCE Do NOT use REVENUE or EXPENSE.';
COMMENT ON COLUMN "Catalogue"."Alert_Required" IS '1 = always notify owner/accountant when this event fires';
COMMENT ON COLUMN "Catalogue"."Posting_Complexity" IS 'SIMPLE=one debit one credit / COMPOUND=two debits or credits / COMPLEX=three or more lines';
COMMENT ON COLUMN "Catalogue"."Narrative_template" IS 'Template for the auto-generated Narrative when this event occurs. Use {placeholders} for dynamic values. Example: \"You sold {Quantity} {Product_Name} to {Stakeholder_Name} for {Amount} today.\"';
COMMENT ON COLUMN "Catalogue"."Evidence_template" IS 'Minimum evidence required before this event can be marked complete. Pipe-separated: RECEIPT|DELIVERY_NOTE or LOAN_AGREEMENT| ID_DOCUMENT|BANK_STATEMENT';
COMMENT ON COLUMN "Catalogue"."Report_sections" IS 'Which report sections this event contributes to, pipe-separated. Example: INCOME_STATEMENT:Revenue|CASH_FLOW:Operating| SUCCESSION_REPORT:Trading_Activity';
COMMENT ON COLUMN "Catalogue"."Logic_rules_to_check" IS 'DEPRECATED for primary gate — use Primary_Logic_id instead. This field is kept for documenting secondary rules the application layer may check. The primary validation gate is now Primary_Logic_id (a real FK, not a comma-separated string). Rule chains: the primary LogicConditions row references child rules via LogicConditions.Parent_Logic, forming a tree: primary gate -> child validation -> sub-rule. Comma-separated LogicConditions_ids to evaluate when this event fires. Example: 1,5,12 — checks double-entry balance, asset disposal rule, revenue recognition gate';
COMMENT ON COLUMN "Catalogue"."Primary_Logic_id" IS 'LogicConditions — the PRIMARY validation gate for this event. This replaces Logic_rules_to_check for the first validation step. The LogicConditions row linked here may reference child rules via Parent_Logic. Example: SELL_ASSET -> Primary_Logic_id -> Is_Fixed_Asset? -> Has_Carrying_Value? -> Disposal_Evidence? -> Calculate_Gain_Loss. This chain is explainable and enforceable; a comma-separated string is neither.';
COMMENT ON COLUMN "Catalogue"."Default_Business_Unit" IS 'The business unit this event normally belongs to. SHOP / FARM / RENTAL / INVESTMENTS / RESTAURANT / GARAGE / MOTEL Provides the default value for Transactions.Business_Unit when the cashier does not specify. Example: SELL_EGGS -> Default_Business_Unit = SHOP Example: HARVEST_BIOLOGICAL_ASSET -> Default_Business_Unit = FARM Example: COLLECT_RENT -> Default_Business_Unit = RENTAL The cashier can override this for unusual cases (farm produce sold direct to customer). Without a default, Business_Unit is often left NULL, breaking profit-by-unit reports.';
COMMENT ON COLUMN "Catalogue"."Effective_From" IS 'When this version of the Catalogue event takes effect. A child looking at a 2020 transaction uses the Catalogue version active in 2020, not the 2026 version. NULL = active from the beginning of records.';
COMMENT ON COLUMN "Catalogue"."Effective_To" IS 'When this version expires. NULL = still active. Example: SELL_EGGS version 1 (2020-2024) was cash only. SELL_EGGS version 2 (2025-) includes M-Pesa and credit.';
COMMENT ON COLUMN "Catalogue"."Version_No" IS 'Version number of this Catalogue event. Increment when accounting treatment changes (new payment methods, VAT introduction, change in standard applied). Never delete old versions.';
COMMENT ON COLUMN "Catalogue"."Is_Active" IS '1 = current active version. 0 = superseded by a later version (kept for historical transaction lookups). Only one row per Event_Name should have Is_Active=1 at any time.';
COMMENT ON COLUMN "Account"."Account_Type" IS 'ASSET / LIABILITY / EQUITY / INCOME / EXPENDITURE';
COMMENT ON COLUMN "Account"."Financial_Statement" IS 'BALANCE_SHEET / INCOME_STATEMENT / CASH_FLOW / EQUITY_STATEMENT';
COMMENT ON COLUMN "Account"."Financial_Statement_Line" IS 'Cash and Cash Equivalents / Trade Receivables / Inventory / PPE / etc.';
COMMENT ON COLUMN "Account"."Measurement_Basis" IS 'HISTORICAL_COST / FAIR_VALUE / NRV / AMORTIZED_COST / PRESENT_VALUE';
COMMENT ON COLUMN "Account"."Normal_Balance" IS 'DEBIT or CREDIT — which side increases this account';
COMMENT ON COLUMN "Account"."Authoritative_Source" IS 'Where the authoritative balance for this account comes from. JOURNAL=SUM(Debit-Credit) from Journal entries (default for accounting accounts). RESOURCE=Resources.Resources_Quantity x unit cost (physical inventory count). MONEY=Money.Outstanding_Amount (loans, bonds, receivables, rent arrears). PAYMENT=Payment records reconciled against bank (cash, M-Pesa). RECORD=Records.Actual_Closing_Cash (daily cash reconciliation). MANUAL_COUNT=entered by owner or accountant from physical count or external statement. EXTERNAL_STATEMENT=verified against bank statement, bond statement, or KRA filing. Prevents the same balance being calculated differently by different reports.';
COMMENT ON COLUMN "Account"."Is_Active" IS '1 = account is active in the chart of accounts';
COMMENT ON COLUMN "Evidence"."Evidence_id" IS '| Priority | Module | | -------- | -------------------------- | | 1 | Source Documents | | 2 | Attachments/OCR | | 3 | Transaction Evidence | | 4 | Audit Trail | | 5 | Tax Documentation | | 6 | Inventory Batch Records | | 7 | Asset Documentation | | 8 | Loan Documentation | | 9 | Compliance Documentation | | 10 | Business Procedures | | 11 | Knowledge Repository | | 12 | Mobile Money Documentation |';
COMMENT ON COLUMN "Evidence"."Account_id" IS 'the record being scored';
COMMENT ON COLUMN "Evidence"."Evidence_level" IS '1=Memory 2=Notebook 3=Receipt 4=Bank 5=Official This is the AVAILABLE evidence level — what actually exists.';
COMMENT ON COLUMN "Evidence"."Required_Evidence_level" IS 'The REQUIRED evidence level for this transaction or record. 1=Memory 2=Notebook 3=Receipt 4=Bank 5=Official Gap: Required_Evidence_level > Evidence_level means the evidence is insufficient. Example: vehicle purchase requires OFFICIAL (5) but only MEMORY (1) is available. The system should flag this gap, not silently treat MEMORY as OFFICIAL.';
COMMENT ON COLUMN "Evidence"."Evidence_Status" IS 'Lifecycle state of this evidence: EXPECTED = evidence is required but not yet collected MISSING = evidence was expected and the deadline has passed without it RECEIVED = evidence has been submitted but not yet verified VERIFIED = evidence has been reviewed and accepted by accountant or owner REJECTED = evidence was reviewed and found insufficient or fraudulent SUPERSEDED = evidence has been replaced by stronger evidence (MEMORY upgraded to RECEIPT) IMPROVED = confidence level has been upgraded without replacing the original record'',';
COMMENT ON COLUMN "Evidence"."Evidence_type" IS 'NONE / PHOTO / RECEIPT / SIGNED / CONTRACT / BANK_RECORD';
COMMENT ON COLUMN "Evidence"."Evidence_Strength" IS '1=Low 2=Medium 3=High 0=Unverified — higher is stronger';
COMMENT ON COLUMN "Evidence"."Source" IS 'description of the source document';
COMMENT ON COLUMN "Evidence"."Verified" IS '0=unverified · 1=verified by trained accountant · 2=verified by certified accountant · 3=verified by owner';
COMMENT ON COLUMN "Evidence"."Confidence_Level" IS '1=Memory 2=Notebook 3=Receipt 4=Bank statement 5=Official document';
COMMENT ON COLUMN "Evidence"."Original_Evidence_level" IS 'The evidence level when this record was FIRST created. Preserved permanently — never overwritten when evidence improves. Example: Vehicle purchased in 2017 recorded from MEMORY (1). Original_Evidence_level = 1. Later, the logbook is found. Evidence_level upgrades to OFFICIAL (5). Original_Evidence_level remains 1 — the historical record of what was known at the time.'',';
COMMENT ON COLUMN "Evidence"."Original_Confidence_Level" IS 'The confidence level when this record was FIRST created. Preserved permanently — never updated when evidence improves.';
COMMENT ON COLUMN "Evidence"."Evidence_Improved_date" IS 'Date when evidence was upgraded (MEMORY -> RECEIPT -> OFFICIAL). NULL = evidence has never been upgraded from its original level.';
COMMENT ON COLUMN "Evidence"."Evidence_Improved_by" IS 'Management — who upgraded the evidence. The accountant who found the logbook; the grandson who retrieved the bank statement.';
COMMENT ON COLUMN "Transactions"."Transactions_id" IS 'for split deliveries/installments';
COMMENT ON COLUMN "Transactions"."Records_id" IS 'Records (Records_type=TRANSACTION_BATCH) — all line items in one customer basket share this Records_id. Eggs + Milk + Bag sold together = 3 Transactions rows, same Records_id. The receipt is generated from the Records row, not from a single Transaction. NULL for non-sale transactions (loan repayments, depreciation, etc.).';
COMMENT ON COLUMN "Transactions"."Correction_of" IS 'Transactions — the original transaction this corrects. The original transaction is NEVER deleted. It remains with Correction_Status=REVERSED. Correcting entries are posted in the current OPEN period, not backdated.';
COMMENT ON COLUMN "Transactions"."Correction_Reason" IS 'Mandatory when Correction_of is set. What was wrong, why it is being corrected, and what the correct position is.';
COMMENT ON COLUMN "Transactions"."Corrected_By" IS 'Management — who authorised this correction. Required when Correction_of is not NULL.';
COMMENT ON COLUMN "Transactions"."Correction_Date" IS 'Date this correction was authorised.';
COMMENT ON COLUMN "Transactions"."Cycle_id" IS 'Root Transactions_id of this business cycle. Opening row: Cycle_id = own Transactions_id. All subsequent stages share this value.';
COMMENT ON COLUMN "Transactions"."Cycle_type" IS 'Standardised 11-value vocabulary — identical across ProcessActions, Catalogue, Transactions: INCOME / EXPENDITURE / INVENTORY / LOAN / RENT / PAYROLL / ASSET / FARMING / INSURANCE / INVESTMENT / INHERITANCE Do NOT use REVENUE or EXPENSE.';
COMMENT ON COLUMN "Transactions"."Cycle_parent" IS 'The immediately preceding Transactions_id in the operational sequence. Cycle_id = root of the entire cycle (never changes within a cycle). Cycle_parent = direct predecessor (changes at each step). Example: T100(parent=NULL) -> T101(parent=100) -> T102(parent=101). This gives both cycle identity (Cycle_id) and event sequence (Cycle_parent chain).';
COMMENT ON COLUMN "Transactions"."Cycle_stage" IS 'The sequence number of this step within the business cycle. Value is taken from ProcessActions.Sequence_No for the action that produced this transaction. Meaning depends on Cycle_type — never interpret Cycle_stage in isolation: INCOME cycle: 1=Order 2=Delivery 3=Invoice 4=Payment LOAN cycle: 1=Drawdown 2=Active 3=Partial_Repayment 4=Final_Repayment FARMING cycle: 1=Plant 2=Grow 3=Harvest 4=Sell ASSET cycle: 1=Purchase 2=In_Use 3=Depreciation 4=Disposal';
COMMENT ON COLUMN "Transactions"."Cycle_status" IS 'OPEN / PARTIAL / CLOSED / CANCELLED';
COMMENT ON COLUMN "Transactions"."Cycle_reference" IS 'Human-readable identifier for this business cycle. Format: {TYPE}-{YEAR}-{SEQUENCE} e.g. SALE-2026-000123 / LOAN-2020-000001 / RENT-2026-000044 Set when a cycle is OPENED (first Transaction row, where Cycle_id = Transactions_id). All subsequent rows in the same cycle share this reference. This is the identifier that appears on receipts, statements, and reports. A child should read SALE-2026-000123, not Cycle ID 9182.';
COMMENT ON COLUMN "Transactions"."Business_Event" IS 'The ECONOMIC EVENT — what happened in the real world. Restricted to events a non-accountant can directly observe: SALE = goods or services transferred to a customer PURCHASE = goods or services received from a supplier PAYMENT = cash or mobile money paid out RECEIPT = cash or mobile money received TRANSFER = movement of goods or cash between business units INHERITANCE = ownership transferred through succession DONATION = asset or resource received without payment LOSS = asset lost through damage, theft, or disposal below cost CAPITAL = owner contribution or withdrawal NOTE: DEPRECIATION and REVALUATION are accounting allocations, not economic events. They belong in Accounting_Event. CORRECTION is an audit action — belongs in Correction_Status. ADJUSTMENT belongs in Accounting_Event as ADJUSTMENT.';
COMMENT ON COLUMN "Transactions"."Transaction_Nature" IS 'Distinguishes the economic nature of this transaction. CRITICAL for multi-business families to prevent double-counting income. EXTERNAL_SALE = goods or services sold to a third party outside the family enterprise EXTERNAL_PURCHASE = goods or services bought from a third party supplier INTERNAL_TRANSFER = movement between business units of the same enterprise (Farm produces milk -> Shop sells milk: the farm-to-shop step is INTERNAL) Internal transfers must be eliminated in consolidated reports OWNER_CONTRIBUTION = owner injects capital into the business OWNER_WITHDRAWAL = owner takes money out (drawings) FAMILY_GIFT = asset or resource given by a family member without consideration INHERITANCE = transfer of ownership through formal succession INTER_UNIT_LOAN = temporary cash transfer between business units (repayable) NULL = nature not yet determined or not applicable Without this field: Farm records milk transfer as i';
COMMENT ON COLUMN "Transactions"."Reference_no" IS 'receipt / invoice no.';
COMMENT ON COLUMN "Transactions"."Tax_rate" IS 'e.g. 16.00 for VAT';
COMMENT ON COLUMN "Transactions"."Business_Unit" IS 'which unit this belongs to: SHOP / FARM / INVESTMENTS / RENTAL / TEACHING';
COMMENT ON COLUMN "Transactions"."Confidence_Level" IS '1=Memory 2=Estimate 3=Verbal 4=Written 5=Documented receipt/bank';
COMMENT ON COLUMN "Transactions"."Operational_Event" IS 'Purchase / Sale / Payment / Investment / Loan / Payroll / Rent / Insurance / Harvest/ Asset Purchase / Asset Disposal';
COMMENT ON COLUMN "Transactions"."Accounting_Event" IS 'The accounting classification of this event: RECOGNITION — first time this item enters the books (new asset, new income earned) SETTLEMENT — cash received or paid against a previously recognised item ACCRUAL — income earned or expense incurred but not yet cash REVERSAL — undoing a prior accrual (at period start) ADJUSTMENT — correction or reclassification within the same period DEPRECIATION — periodic allocation of fixed asset cost (IAS 16) REVALUATION — change in fair value (IAS 41 biological assets, IAS 40 investment property) IMPAIRMENT — write-down below carrying value (IFRS 9, IAS 36) TRANSFER — movement between categories (biological asset → inventory at harvest point)';
COMMENT ON COLUMN "Transactions"."Evidence_id" IS 'Evidence_Level - the evidence record supporting this transaction';
COMMENT ON COLUMN "Payment"."Payment_id" IS 'Financial Arrangement contains: debt, interest, duration, repayment, obligations.';
COMMENT ON COLUMN "Payment"."Money_id" IS 'Money — the instrument this payment settles.';
COMMENT ON COLUMN "Payment"."Payment_type" IS 'cash/ Mobile / bank cheque/ bank transfer';
COMMENT ON COLUMN "Payment"."Payment_Method" IS 'Cash / Bank / M-Pesa / Airtel Money / MTN Mobile Money / Orange Money / Ecocash / Wave / Cheque / Credit / Cryptocurrency';
COMMENT ON COLUMN "Payment"."Mobile_money_provider" IS 'Airtel-Money / MTN / M-Pesa';
COMMENT ON COLUMN "Payment"."Mobile_money_ref" IS 'confirmation code';
COMMENT ON COLUMN "Payment"."Payment_Transaction_Reference" IS 'M-Pesa confirmation code, bank reference, or POS receipt number. Used in the UNIQUE constraint with Payment_Method to prevent duplicate entries. e.g. QHG7R2K8P9 (M-Pesa) / TXN-20260717-001 (bank)';
COMMENT ON COLUMN "Payment"."Payment_Reference" IS 'Human-readable payment reference for the receipt and document. e.g. PAY-2026-07-0042 — generated by the application, not by the payment provider.';
COMMENT ON COLUMN "Payment"."Payment_Amount" IS 'Total amount settled by this payment. May differ from the invoice amount for partial payments. Used to determine Outstanding_Amount on Income and Expenditure rows.';
COMMENT ON COLUMN "Money"."Money_id" IS 'holds non-inventory financial instruments: trade debt with named customers, supplier credit, rent arrears, money market placements, insurance policies.';
COMMENT ON COLUMN "Money"."Asset_id" IS 'populated when instrument is backed by a physical asset';
COMMENT ON COLUMN "Money"."Instrument_type" IS 'CUSTOMER_DEBT / SUPPLIER_CREDIT / RENT_ARREARS / MONEY_MARKET / INSURANCE / LOAN';
COMMENT ON COLUMN "Money"."Instrument_Class" IS 'IFRS 9: AMORTIZED_COST / FAIR_VALUE_OCI / FAIR_VALUE_PNL / OPERATING_ASSET / OPERATING_LIABILITY';
COMMENT ON COLUMN "Money"."Accounting_Treatment" IS 'HISTORICAL_COST / AMORTIZED_COST_EIR / FAIR_VALUE_MARKET / FAIR_VALUE_MODEL / LOWER_OF_COST_NRV';
COMMENT ON COLUMN "Money"."Money_Status" IS 'ACTIVE/OVERDUE/PAID/DEFAULTED/MATURED/CLOSED';
COMMENT ON COLUMN "Money"."Repayment_Frequency" IS 'DAILY/WEEKLY/MONTHLY/SEASONAL';
COMMENT ON COLUMN "Money"."Risk_Level" IS 'LOW/MEDIUM/HIGH';
COMMENT ON COLUMN "Money"."Outstanding_Amount" IS 'Principal_amount minus payments received';
COMMENT ON COLUMN "Money"."Due_Date" IS 'When payment or settlement is expected';
COMMENT ON COLUMN "Account_History"."Old_Balance" IS 'balance before this entry';
COMMENT ON COLUMN "Account_History"."Debit" IS 'amount debited';
COMMENT ON COLUMN "Account_History"."Credit" IS 'amount credited';
COMMENT ON COLUMN "Account_History"."New_Balance" IS 'balance after this entry';
COMMENT ON COLUMN "Account_History"."Balance_Type" IS 'Opening Periodic Adjustment Closing Correction';
COMMENT ON COLUMN "Account_History"."Reason" IS 'plain language explanation';
COMMENT ON COLUMN "Account_History"."Entry_date" IS 'when this happened';
COMMENT ON COLUMN "Account_History"."Created_at" IS 'when recorded';
COMMENT ON COLUMN "Account_History"."Author" IS 'who recorded or triggered this history entry';
COMMENT ON COLUMN "Account_History"."Approved_by" IS 'who approved this change (required for BLOCK-level rule entries)';
COMMENT ON COLUMN "Account_History"."Approval_date" IS 'When approval was granted';
COMMENT ON COLUMN "Account_History"."Previous_value" IS 'Previous state of a non-balance field e.g. old Account_Name or old Account_Type';
COMMENT ON COLUMN "Account_History"."New_value" IS 'New state of the changed field';
COMMENT ON COLUMN "Account_History"."Trigger_rule" IS 'which rule caused this history entry, if automated';
COMMENT ON COLUMN "Narrative"."Account_id" IS 'the ID of the record being described';
COMMENT ON COLUMN "Narrative"."Narrative_type" IS 'What kind of narrative this is and for what purpose: TRANSACTION_EXPLANATION = plain description of what happened in one event DAILY_SUMMARY = summary of all events in one business day WEEKLY_SUMMARY = summary of the week for owner review ACCOUNTING_EXPLANATION = technical accounting treatment with standard references MANAGEMENT_EXPLANATION = trend and performance commentary for decisions BANK_EXPLANATION = formal narrative suitable for bank submissions SUCCESSION_EXPLANATION = explanation written for the future inheritor ALERT_EXPLANATION = explanation accompanying a WARN or BLOCK rule result CORRECTION_EXPLANATION = describes what was wrong and how it was corrected MEMORY = owner or family recollection of a historical event ORIGIN = why this account, resource, or obligation came into existence CONTEXT = background information that explains the business environment';
COMMENT ON COLUMN "Narrative"."Narrative_audience" IS 'Who this narrative is written for. One transaction can generate multiple narratives for different audiences from one event: OWNER = plain language, local context (You sold 7 trays of eggs today.) ACCOUNTANT = accounting language (Inventory decreased. Operating income recognised. IFRS 15.) BANK = formal language suitable for bank statements or loan applications SUCCESSOR = explanation for the future inheritor (Eggs are normally purchased weekly...) ALL = universal narrative suitable for any audience Works with Is_Generated: system-generated narratives (Is_Generated=1) may produce OWNER and ACCOUNTANT versions simultaneously from the same Catalogue event.';
COMMENT ON COLUMN "Narrative"."Is_Generated" IS '1=System generated (automatic explanation of what happened) 0=Human authored (written by owner, accountant, or family member)';
COMMENT ON COLUMN "Narrative"."Generated_from_catalogue" IS 'which event template produced this narrative';
COMMENT ON COLUMN "Narrative"."Narrative_source" IS 'SYSTEM / OWNER / ACCOUNTANT / FAMILY / AUDITOR / BANK';
COMMENT ON COLUMN "Narrative"."Description" IS 'the story · any length · any language';
COMMENT ON COLUMN "Narrative"."Language" IS 'en / sw / ha / yo / am / fr';
COMMENT ON COLUMN "Narrative"."Author" IS 'who wrote this';
COMMENT ON COLUMN "Knowledge"."Explanation" IS 'plain language description of this record';
COMMENT ON COLUMN "Knowledge"."Knowledge_type" IS 'EXPLANATION / RECOMMENDATION / LESSON_LEARNED / DECISION_REASON / ALTERNATIVE_CONSIDERED / WARNING / POLICY';
COMMENT ON COLUMN "Knowledge"."Decision_Reason" IS 'Why a specific business decision was made at a specific time. Example: Switched from goats to poultry because drought reduced pasture availability in 2022. Different from Lesson_Learned (what was discovered) — this is why a choice was made.';
COMMENT ON COLUMN "Knowledge"."Alternative_Considered" IS 'What other options were evaluated and why they were not chosen. Example: Considered sheep farming but rejected due to predator losses in the area.';
COMMENT ON COLUMN "Knowledge"."Context" IS 'SEASONAL / CRISIS / SUCCESSION / EXPANSION / CONTRACTION / REGULATORY / FAMILY';
COMMENT ON COLUMN "Knowledge"."Confidence_Level" IS '1=Uncertain 2=Probable 3=Based on experience 4=Verified 5=Formally documented';
COMMENT ON COLUMN "Knowledge"."Language" IS 'sw / en / ha / yo / am';
COMMENT ON COLUMN "Knowledge"."Audience" IS 'Management role that is the intended audience. References a role (OWNER/ACCOUNTANT/ADVISOR/SUCCESSOR), not a named person.Not a free-text field — must reference';
COMMENT ON COLUMN "Knowledge"."Author" IS 'who wrote this explanation';
