-- Generated: Postgres port of project_plan5b.sql
-- FKs separated into a second pass to resolve circular table dependencies

CREATE TABLE IF NOT EXISTS "Stakeholder" (
  "Stakeholder_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "First_name" VARCHAR(45) NULL,
  "Last_name" VARCHAR(45) NULL,
  "Business_name" VARCHAR(150) NULL,
  "ID_Number" VARCHAR(45) NULL,
  "ID_type" VARCHAR(45) NULL,
  "Location" VARCHAR(45) NULL,
  "Address" VARCHAR(45) NULL,
  "Email_1" VARCHAR(45) NULL,
  "Tel_1" VARCHAR(45) NULL,
  "Tel_2" VARCHAR(45) NULL,
  "Email_2" VARCHAR(45) NULL,
  "Website" VARCHAR(150) NULL,
  "Stakeholder_Category" VARCHAR(45) NULL,
  "Stakeholder_Role" VARCHAR(45) NULL,
  "Relationship_to_owner" VARCHAR(45) NULL,
  "Relationship_Status" VARCHAR(45) NULL,
  PRIMARY KEY ("Stakeholder_id")
);

CREATE TABLE IF NOT EXISTS "Product" (
  "Product_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Stakeholder_id" INT NULL,
  "Product_type" VARCHAR(45) NULL,
  "Product_Name" VARCHAR(45) NULL,
  "Product_Price" DECIMAL(15, 2) NULL,
  "Product_Rate" DECIMAL(15, 2) NULL,
  "Product_Provider" INT NULL,
  "Product_Unit" VARCHAR(45) NULL,
  "Product_Category" VARCHAR(45) NULL,
  "Product_Barcode" VARCHAR(45) NULL,
  "Product_Cost" DECIMAL(15, 2) NULL,
  "Product_Reorder_Level" DECIMAL(15, 3) NULL,
  "Product_Expiry_Tracking" SMALLINT NULL DEFAULT 0,
  "Is_Asset" SMALLINT NULL DEFAULT 0,
  "Is_Service" SMALLINT NULL DEFAULT 0,
  PRIMARY KEY ("Product_id")
);

CREATE TABLE IF NOT EXISTS "ProcessActions" (
  "ProcessActions_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Process_name" VARCHAR(45) NOT NULL,
  "Action_Type" VARCHAR(20) NULL,
  "Cycle_type" VARCHAR(20) NULL,
  "Sequence_No" INT NULL,
  "Accounting_Event" SMALLINT NULL DEFAULT 0,
  "Operational_Event" SMALLINT NULL DEFAULT 0,
  "From_State" VARCHAR(20) NULL,
  "To_State" VARCHAR(20) NULL,
  "Applies_To" VARCHAR(20) NULL,
  "Affects_Cash" SMALLINT NULL DEFAULT 0,
  "Affects_Resources" SMALLINT NULL DEFAULT 0,
  "Requires_Approval" SMALLINT NULL DEFAULT 0,
  "Approval_Level" VARCHAR(20) NULL,
  "ParentAction_id" INT NULL,
  "Process_Description" VARCHAR(255) NULL,
  "Default_Journal_Template" VARCHAR(45) NULL,
  "Evidence_Event" SMALLINT NULL,
  "Reversal_Method" VARCHAR(20) NULL,
  "Required_Document" VARCHAR(45) NULL,
  "Required_Evidence" VARCHAR(45) NULL,
  "Scheduled_date" VARCHAR(45) NULL,
  "Is_Recurring" SMALLINT NULL,
  "Recurrence_Pattern" VARCHAR(20) NULL,
  PRIMARY KEY ("ProcessActions_id")
);

CREATE TABLE IF NOT EXISTS "LogicConditions" (
  "LogicConditions_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NULL,
  "Account_id" INT NULL,
  "Structure_id" INT NULL,
  "Parent_Logic" INT NULL,
  "Conditons_Name" VARCHAR(45) NULL,
  "When_Event" VARCHAR(20) NULL,
  "Then_Actions" TEXT NULL,
  "Else_Actions" TEXT NULL,
  "Owner_Message" VARCHAR(255) NULL,
  "Accountant_Message" VARCHAR(255) NULL,
  "System_Action" VARCHAR(100) NULL,
  "Left_Operand" VARCHAR(100) NULL,
  "Operator" VARCHAR(10) NULL,
  "Right_Operand" VARCHAR(100) NULL,
  "Check_Expression" VARCHAR(500) NULL,
  "Enforcement" VARCHAR(10) NULL,
  "Review_Level" VARCHAR(20) NULL,
  "Fact_Type" VARCHAR(15) NULL,
  "Confidence_Level" SMALLINT NULL,
  "Logic_Explanation" TEXT NULL,
  "Failure_Message" VARCHAR(255) NULL,
  "Logic_type" VARCHAR(20) NULL,
  "Rule_Result" VARCHAR(15) NULL,
  "Rule_Reason" VARCHAR(30) NULL,
  "Rule_Override_by" INT NULL,
  "Rule_Override_date" DATE NULL,
  "Rule_Override_reason" VARCHAR(255) NULL,
  PRIMARY KEY ("LogicConditions_id")
);

CREATE TABLE IF NOT EXISTS "Resources" (
  "Resources_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Product_id" INT NOT NULL,
  "Resource_type" VARCHAR(20) NULL,
  "Resource_Class" VARCHAR(20) NULL,
  "Resource_Category" VARCHAR(45) NULL,
  "Consumption_Method" VARCHAR(20) NULL,
  "Records_id" INT NULL,
  "Stakeholder_id" INT NULL,
  "Resources_Quantity" DECIMAL(15, 3) NULL,
  "Fair_Value" DECIMAL(15, 2) NULL,
  "Fair_Value_Date" DATE NULL,
  "Fair_Value_Basis" VARCHAR(25) NULL,
  "Resources_Price" DECIMAL(15, 2) NULL,
  "Unit_Cost" DECIMAL(15, 2) NULL,
  "Margin_rate" DECIMAL(5, 2) NULL,
  "Resources_Life" VARCHAR(45) NULL,
  "Resources_Quality" VARCHAR(45) NULL,
  "Resources_Status" VARCHAR(20) NULL,
  "Resources_Source" VARCHAR(20) NULL,
  "Resources_Purchase_Document" VARCHAR(255) NULL,
  "Inventory_Batch_Number" VARCHAR(45) NULL,
  "Resources_Manufacture_Date" DATE NULL,
  "Resources_Expiry_Date" DATE NULL,
  "Last_updated" TIMESTAMP NULL,
  "Selling_Price" DECIMAL(15, 2) NULL,
  PRIMARY KEY ("Resources_id")
);

CREATE TABLE IF NOT EXISTS "Assets" (
  "Assets_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "Account_id" INT NOT NULL,
  "Records_id" INT NOT NULL,
  "Assets_Type" VARCHAR(45) NULL,
  "Asset_Classification" VARCHAR(20) NULL,
  "Cost_Amount" DECIMAL(15, 2) NULL,
  "Residual_Value" DECIMAL(15, 2) NULL DEFAULT 0,
  "Useful_Life_Years" DECIMAL(15, 2) NULL,
  "Depreciation_Method" VARCHAR(20) NULL,
  "Accumulated_Depreciation" DECIMAL(15, 2) NULL DEFAULT 0,
  "Accumulated_Impairment" DECIMAL(15, 2) NULL DEFAULT 0,
  "Carrying_Amount" DECIMAL(15, 2) NULL,
  "Acquisition_Date" DATE NULL,
  "Placed_In_Service_Date" DATE NULL,
  "Disposal_Date" DATE NULL,
  "Net_Amount" DECIMAL(15, 2) NULL,
  "Period" DATE NULL,
  "Period_end" DATE NULL,
  PRIMARY KEY ("Assets_id")
);

CREATE TABLE IF NOT EXISTS "Equity" (
  "Equity_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "Account_id" INT NOT NULL,
  "Records_id" INT NOT NULL,
  "Equity_type" VARCHAR(45) NULL,
  "Net_Amount" DECIMAL(15, 2) NULL,
  "Period" DATE NULL,
  "Period_end" DATE NULL,
  PRIMARY KEY ("Equity_id")
);

CREATE TABLE IF NOT EXISTS "Liability" (
  "Liability_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "Account_id" INT NOT NULL,
  "Records_id" INT NOT NULL,
  "Liability_Type" VARCHAR(45) NULL,
  "Liability_Classification" VARCHAR(20) NULL,
  "Net_Amount" DECIMAL(15, 2) NULL,
  "Period" DATE NULL,
  "Period_end" DATE NULL,
  PRIMARY KEY ("Liability_id")
);

CREATE TABLE IF NOT EXISTS "Income" (
  "Income_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "Account_id" INT NOT NULL,
  "Records_id" INT NOT NULL,
  "Transactions_id" INT NULL,
  "Income_type" VARCHAR(45) NULL,
  "Income_Source" VARCHAR(45) NULL,
  "Income_Category" VARCHAR(45) NULL,
  "Income_Recognition" VARCHAR(10) NULL,
  "Recognition_Method" VARCHAR(20) NULL,
  "Is_Recurring" SMALLINT NULL DEFAULT 0,
  "Accounting_Nature" VARCHAR(25) NULL,
  "Business_Unit" VARCHAR(20) NULL,
  "Marketing_Channel" VARCHAR(45) NULL,
  "Standard_Reference" VARCHAR(45) NULL,
  "Net_Amount" DECIMAL(15, 2) NULL,
  "Cash_Received" DECIMAL(15, 2) NULL,
  "Outstanding_Amount" DECIMAL(15, 2) NULL,
  "Period_id" INT NULL,
  "Period" DATE NULL,
  "Period_end" DATE NULL,
  PRIMARY KEY ("Income_id")
);

CREATE TABLE IF NOT EXISTS "Expenditure" (
  "Expenditure_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "Account_id" INT NOT NULL,
  "Records_id" INT NOT NULL,
  "Transactions_id" INT NULL,
  "Expenditure_type" VARCHAR(45) NULL,
  "Expenditure_subtype" VARCHAR(20) NULL,
  "Is_Prepaid" SMALLINT NULL DEFAULT 0,
  "Billing_Reference" VARCHAR(45) NULL,
  "Consumption_Unit" DECIMAL(15, 3) NULL,
  "Expenditure_Category" VARCHAR(45) NULL,
  "Expenditure_Behaviour" VARCHAR(10) NULL,
  "Expenditure_Frequency" VARCHAR(10) NULL,
  "Business_Unit" VARCHAR(20) NULL,
  "Expenditure_Paid" DECIMAL(15, 2) NULL,
  "Expenditure_Outstanding" DECIMAL(15, 2) NULL,
  "Net_Amount" DECIMAL(15, 2) NULL,
  "Period_id" INT NULL,
  "Period" DATE NULL,
  "Period_end" DATE NULL,
  "Is_Capitalizable" SMALLINT NULL DEFAULT 0,
  "Capital_Treatment" VARCHAR(20) NULL DEFAULT 'EXPENSE',
  "Accounting_Nature" VARCHAR(25) NULL,
  PRIMARY KEY ("Expenditure_id")
);

CREATE TABLE IF NOT EXISTS "Journal" (
  "Journal_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NOT NULL,
  "Correction_of" INT NULL,
  "Correction_Reason" VARCHAR(255) NULL,
  "Corrected_By" INT NULL,
  "Correction_Date" DATE NULL,
  "Correction_Status" VARCHAR(15) NULL DEFAULT 'ORIGINAL',
  "Catalogue_id" INT NOT NULL,
  "Transactions_id" INT NULL,
  "Administration_id" INT NULL,
  "Product_id" INT NULL,
  "Debit" DECIMAL(15, 2) NULL,
  "Credit" DECIMAL(15, 2) NULL,
  "Running_Balance" DECIMAL(15, 2) NULL,
  "Net_Amount" DECIMAL(15, 2) NULL,
  "Created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Transaction_Date" DATE NULL,
  "Posting_Date" DATE NULL,
  "Period_id" INT NULL,
  "Description" VARCHAR(255) NULL,
  "Recognition_Basis" VARCHAR(10) NULL,
  PRIMARY KEY ("Journal_id")
);

CREATE TABLE IF NOT EXISTS "Reports" (
  "Reports_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NULL,
  "Journal_id" INT NULL,
  "Ledger_id" INT NULL,
  "Transactions_id" INT NULL,
  "Records_id" INT NULL,
  "Reports_type" VARCHAR(45) NULL,
  "Report_category" VARCHAR(20) NULL,
  "Reports_period" DATE NULL,
  "Reports_Period_Start" TIMESTAMP NULL,
  "Reports_Period_End" TIMESTAMP NULL,
  "Reports_NetValue" DECIMAL(15, 2) NULL,
  "CF_Category" VARCHAR(20) NULL,
  "CF_Operating" DECIMAL(15, 2) NULL,
  "CF_Investing" DECIMAL(15, 2) NULL,
  "CF_Financing" DECIMAL(15, 2) NULL,
  "Free_Cash_Flow" DECIMAL(15, 2) NULL,
  "Net_Profit" DECIMAL(15, 2) NULL,
  "Report_basis" VARCHAR(10) NULL,
  "Report_Stage" VARCHAR(30) NULL,
  "Is_Adjusted" SMALLINT NULL DEFAULT 0,
  "Parent_Report_id" INT NULL DEFAULT 0,
  "Adjustment_count" INT NULL DEFAULT 0,
  PRIMARY KEY ("Reports_id")
);

CREATE TABLE IF NOT EXISTS "Ledger" (
  "Ledger_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NULL,
  "Journal_id" INT NULL,
  "Administration_id" INT NULL,
  "Asset_id" INT NULL,
  "Liablity_id" INT NULL,
  "Equity_id" INT NULL,
  "Income_id" INT NULL,
  "Expenditure_id" INT NULL,
  "Transactions_id" INT NULL,
  "Ledger_Name" VARCHAR(100) NULL,
  "Ledger_Description" VARCHAR(255) NULL,
  "Ledger_Amount" DECIMAL(15, 2) NULL,
  "Ledger_Total" DECIMAL(15, 2) NULL,
  "Parent_Report_id" INT NULL DEFAULT 0,
  "Report_Stage" INT NULL DEFAULT 0,
  PRIMARY KEY ("Ledger_id")
);

CREATE TABLE IF NOT EXISTS "Organisation" (
  "Entreprise_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Administration_id" INT NULL,
  "Account_id" INT NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "Ledger_id" INT NULL,
  "Resources_id" INT NULL,
  "Product_id" INT NULL,
  "Equity_id" INT NULL,
  "Asset_id" INT NULL,
  "Transaction_id" INT NULL,
  "Organisational_Name" VARCHAR(45) NULL,
  "Organisation_category" VARCHAR(45) NULL,
  "Organisation_Value" DECIMAL(15, 2) NULL,
  "Industry" VARCHAR(45) NULL,
  "Business_Units" TEXT NULL,
  "Organisation_Type" VARCHAR(45) NULL,
  "Organisation_Address" VARCHAR(45) NULL,
  "Country" VARCHAR(100) NULL,
  "Business_Maturity" DECIMAL(15, 2) NULL,
  "Fiscal_Year_Start" DATE NULL,
  "Fiscal_Year" DATE NULL,
  "Organisation_Currency" VARCHAR(45) NULL,
  "Organisation_Country" VARCHAR(45) NULL,
  "Worth_Estimated" DECIMAL(15, 3) NULL,
  "Worth_Book_Value" DECIMAL(15, 3) NULL,
  "Worth_Method" VARCHAR(20) NULL,
  "Worth_Date" DATE NULL,
  PRIMARY KEY ("Entreprise_id")
);

CREATE TABLE IF NOT EXISTS "Records" (
  "Records_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "Transactions_id" INT NULL,
  "Administration_id" INT NULL,
  "Entreprise_id" INT NULL,
  "Records_Totals" DECIMAL(15, 2) NULL,
  "Records_type" VARCHAR(20) NULL,
  "Records_date" DATE NULL,
  "Period_start" TIMESTAMP NULL,
  "Period_end" TIMESTAMP NULL,
  "Business_Unit" VARCHAR(45) NULL,
  "Total_Income" DECIMAL(15, 2) NULL DEFAULT 0,
  "Total_Expenditure" DECIMAL(15, 2) NULL DEFAULT 0,
  "Total_Cash_In" DECIMAL(15, 2) NULL DEFAULT 0,
  "Total_Cash_Out" DECIMAL(15, 2) NULL DEFAULT 0,
  "Transaction_Count" INT NULL DEFAULT 0,
  "Net_Position" DECIMAL(15, 2) NULL DEFAULT 0,
  "Structures_id" INT NULL,
  "Period_id" INT NULL,
  "Opening_Cash" DECIMAL(15, 2) NULL DEFAULT 0,
  "Expected_Closing_Cash" DECIMAL(15, 2) NULL DEFAULT 0,
  "Actual_Closing_Cash" DECIMAL(15, 2) NULL DEFAULT 0,
  "Cash_Variance" DECIMAL(15, 2) NULL DEFAULT 0,
  "Stock_Reconciliation" JSON NULL,
  "Batch_Status" VARCHAR(10) NULL DEFAULT 'OPEN',
  PRIMARY KEY ("Records_id")
);

CREATE TABLE IF NOT EXISTS "Documents" (
  "Document_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Reports_id" INT NULL,
  "Cycle_id" INT NULL,
  "Transactions_id" INT NULL,
  "Document_type" VARCHAR(45) NULL,
  "Documents_no" VARCHAR(45) NULL,
  "Documents_version" INT NULL,
  "Stakeholder_id" INT NULL,
  "Organisation_id" INT NULL,
  "Document_Title" VARCHAR(45) NULL,
  "Action" VARCHAR(45) NULL,
  "Device" VARCHAR(45) NULL,
  "Document_date" DATE NULL,
  "Due_date" DATE NULL,
  "Gross_amount" DECIMAL(15, 2) NULL,
  "Tax_amount" DECIMAL(15, 2) NULL,
  "Net_Amount" DECIMAL(15, 2) NULL,
  "Document_status" VARCHAR(45) NULL,
  "Document_Authenticity" VARCHAR(20) NULL,
  "Is_Original" SMALLINT NULL,
  "Is_Legally_Signed" SMALLINT NULL,
  "Is_Digitally_Signed" SMALLINT NULL,
  "Is_Witnessed" SMALLINT NULL,
  "Expiry_date" DATE NULL,
  "Issued_by" VARCHAR(100) NULL,
  "Custodian" INT NULL,
  "File_path" VARCHAR(255) NULL,
  "File_Format" VARCHAR(45) NULL,
  "File_Hash" VARCHAR(45) NULL,
  "Generated" SMALLINT NULL,
  "Generated_By" INT NULL,
  "Approved_By" INT NULL,
  "Confidence_Level" SMALLINT NULL DEFAULT 1,
  "Notes" TEXT NULL,
  "Modified_by" INT NULL,
  "Created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("Document_id")
);

CREATE TABLE IF NOT EXISTS "Management" (
  "Administration_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NOT NULL,
  "LogicConditons_id" INT NULL,
  "ProcessActions_id" INT NULL,
  "Stakeholder_id" INT NULL,
  "Records_id" INT NULL,
  "Product_id" INT NULL,
  "Review_Level" VARCHAR(45) NULL,
  "Administration_type" VARCHAR(45) NULL,
  "Inheritance_Status" VARCHAR(20) NULL,
  "Management_Role" VARCHAR(45) NULL,
  "Management_Name" VARCHAR(45) NULL,
  "Management_Cost" DECIMAL(15, 2) NULL,
  "Arrangement_Type" VARCHAR(20) NULL,
  "Arrangement_Rate" DECIMAL(5, 2) NULL,
  "Access_Level" VARCHAR(20) NULL,
  "Organisation_id" INT NULL,
  "Document_id" INT NULL,
  PRIMARY KEY ("Administration_id")
);

CREATE TABLE IF NOT EXISTS "Structures" (
  "Structures_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Parent_Structure_id" INT NULL,
  "Structure_Level" VARCHAR(15) NULL,
  "Account_id" INT NULL,
  "Structures_Type" VARCHAR(45) NULL,
  "Effective_From" DATE NULL,
  "Effective_To" DATE NULL,
  "Mandatory" SMALLINT NULL DEFAULT 0,
  "Compliance_Level" VARCHAR(20) NULL,
  "Business_Maturity" VARCHAR(20) NULL,
  "Escalation_Role" VARCHAR(20) NULL,
  "Measurement_Basis" VARCHAR(20) NULL,
  "Created_By" INT NULL,
  "Approved_By" INT NULL,
  "Framework_Name" VARCHAR(20) NULL,
  "Framework_Version" VARCHAR(20) NULL,
  "Framework_Priority" SMALLINT NULL,
  "Rule_Code" VARCHAR(20) NULL,
  "Standard_Reference" VARCHAR(45) NULL,
  "Rule_Severity" VARCHAR(10) NULL,
  "Applies_To_Table" VARCHAR(45) NULL,
  "Structures_Name" VARCHAR(45) NULL,
  "Structures_Rule" VARCHAR(45) NULL,
  "Structures_Condition" VARCHAR(45) NULL,
  "Structures_Description" VARCHAR(255) NULL,
  "Recognition_Method" VARCHAR(45) NULL,
  "Structures_Period" DATE NULL,
  "Preference_key" VARCHAR(255) NULL,
  "Preference_value" VARCHAR(255) NULL,
  "Period_Status" VARCHAR(10) NULL DEFAULT 'OPEN',
  "Period_name" VARCHAR(45) NULL,
  PRIMARY KEY ("Structures_id")
);

CREATE TABLE IF NOT EXISTS "Account_codes" (
  "Account_codes_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Code" VARCHAR(10) NOT NULL,
  "Code_name" VARCHAR(100) NOT NULL,
  "Code_categories" VARCHAR(45) NULL,
  "Standard_Reference" VARCHAR(45) NULL,
  "Parent_code_id" INT NULL,
  "Statement_Section" VARCHAR(45) NULL,
  "Is_Active" SMALLINT NOT NULL DEFAULT 1,
  PRIMARY KEY ("Account_codes_id")
);

CREATE TABLE IF NOT EXISTS "Catalogue" (
  "Catalogue_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "LogicConditons_id" INT NULL,
  "Structures_id" INT NULL,
  "ProcessActions_id" INT NULL,
  "Event_Name" VARCHAR(45) NULL,
  "Event_Description" VARCHAR(255) NULL,
  "Debit_Account_code" VARCHAR(10) NULL,
  "Credit_Account_code" VARCHAR(10) NULL,
  "Secondary_Debit_code" VARCHAR(10) NULL,
  "Secondary_Credit_code" VARCHAR(10) NULL,
  "Debit_Account_fk_id" INT NULL,
  "Credit_Account_fk_id" INT NULL,
  "Secondary_Debit_fk_id" INT NULL,
  "Secondary_Credit_fk_id" INT NULL,
  "Cash_Flow_Category" VARCHAR(15) NULL,
  "Operational_Impact" VARCHAR(45) NULL,
  "Risk_Level" VARCHAR(10) NULL,
  "Documentation_type" VARCHAR(45) NULL,
  "Report_trigger" VARCHAR(45) NULL,
  "Escalation_Role" VARCHAR(45) NULL,
  "Cycle_type" VARCHAR(20) NULL,
  "Alert_Required" SMALLINT NULL,
  "Posting_Complexity" VARCHAR(10) NULL,
  "Narrative_template" TEXT NULL,
  "Evidence_template" VARCHAR(100) NULL,
  "Report_sections" TEXT NULL,
  "Review_Level_copy1" VARCHAR(45) NULL,
  "Logic_rules_to_check" VARCHAR(255) NULL,
  "Primary_Logic_id" INT NULL,
  "Account_id" INT NULL,
  "Review_Level" VARCHAR(45) NULL,
  "Default_Business_Unit" VARCHAR(20) NULL,
  "Effective_From" DATE NULL,
  "Effective_To" DATE NULL,
  "Version_No" INT NULL,
  "Is_Active" SMALLINT NULL,
  PRIMARY KEY ("Catalogue_id")
);

CREATE TABLE IF NOT EXISTS "Account" (
  "Account_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Catalogue_id" INT NULL,
  "Product_id" INT NULL,
  "Stakeholder_id" INT NULL,
  "Origin_Record_id" INT NULL,
  "Account_Name" VARCHAR(100) NULL,
  "Account_Type" VARCHAR(45) NULL,
  "Account_Code_id" INT NULL,
  "Account_subType" VARCHAR(45) NULL,
  "Financial_Statement" VARCHAR(25) NULL,
  "Financial_Statement_Line" VARCHAR(100) NULL,
  "Measurement_Basis" VARCHAR(20) NULL,
  "Normal_Balance" VARCHAR(10) NULL,
  "Authoritative_Source" VARCHAR(20) NULL,
  "Current_Balance" DECIMAL(15, 2) NULL,
  "Created_at" TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  "Is_Active" SMALLINT NULL,
  PRIMARY KEY ("Account_id")
);

CREATE TABLE IF NOT EXISTS "Evidence" (
  "Evidence_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NULL,
  "Transactions_id" INT NULL,
  "Records_id" INT NULL,
  "Evidence_level" INT NULL,
  "Required_Evidence_level" INT NULL,
  "Evidence_Status" VARCHAR(15) NULL,
  "Evidence_type" VARCHAR(45) NULL,
  "Evidence_Strength" SMALLINT NULL,
  "Source" VARCHAR(255) NULL,
  "Document_id" INT NULL,
  "Verified" INT NULL,
  "Verified_by" INT NULL,
  "Entry_date" TIMESTAMP NULL,
  "Confidence_Level" INT NULL DEFAULT 1,
  "Original_Evidence_level" INT NULL,
  "Original_Confidence_Level" INT NULL,
  "Evidence_Improved_date" DATE NULL,
  "Evidence_Improved_by" INT NULL,
  PRIMARY KEY ("Evidence_id")
);

CREATE TABLE IF NOT EXISTS "Transactions" (
  "Transactions_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NOT NULL,
  "Records_id" INT NULL,
  "Correction_of" INT NULL,
  "Correction_Reason" VARCHAR(255) NULL,
  "Corrected_By" INT NULL,
  "Correction_Date" DATE NULL,
  "Correction_Status" VARCHAR(15) NULL DEFAULT 'ORIGINAL',
  "Cycle_id" INT NULL,
  "Cycle_type" VARCHAR(20) NULL,
  "Cycle_parent" INT NULL,
  "Cycle_stage" INT NULL,
  "Cycle_status" VARCHAR(20) NULL,
  "Cycle_reference" VARCHAR(45) NULL,
  "Product_id" INT NOT NULL,
  "ProcessActions_id" INT NULL,
  "Transactions_date" TIMESTAMP NOT NULL,
  "Quantity" DECIMAL(15, 3) NULL,
  "Amount" DECIMAL(15, 2) NULL,
  "Business_Event" VARCHAR(45) NULL,
  "Transaction_Nature" VARCHAR(20) NULL,
  "Reference_no" VARCHAR(45) NULL,
  "Tax_rate" DECIMAL(5, 2) NULL,
  "Tax_amount" DECIMAL(15, 2) NULL,
  "Created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "Description" VARCHAR(255) NULL,
  "Business_Unit" VARCHAR(20) NULL,
  "Confidence_Level" SMALLINT NOT NULL DEFAULT 4,
  "Operational_Event" VARCHAR(45) NULL,
  "Accounting_Event" VARCHAR(45) NULL,
  "Evidence_id" INT NULL,
  PRIMARY KEY ("Transactions_id")
);

CREATE TABLE IF NOT EXISTS "Payment" (
  "Payment_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Money_id" INT NULL,
  "Product_id" INT NOT NULL,
  "Records_id" INT NULL,
  "Payment_type" VARCHAR(45) NULL,
  "Payment_Status" VARCHAR(20) NULL,
  "Payment_Due_Date" DATE NULL,
  "Payment_Received_Date" DATE NULL,
  "Payment_Method" VARCHAR(45) NULL,
  "Payment_Price" DECIMAL(15, 2) NULL,
  "Payment_Quantity" DECIMAL(15, 3) NULL,
  "Payment_Duration" VARCHAR(45) NULL,
  "Inventory_Cost" DECIMAL(15, 2) NULL,
  "Mobile_money_provider" VARCHAR(45) NULL,
  "Mobile_money_ref" VARCHAR(45) NULL,
  "Till_Number" VARCHAR(45) NULL,
  "Paybill_Number" VARCHAR(45) NULL,
  "Payment_Phone_Number" VARCHAR(45) NULL,
  "Payment_Transaction_Reference" VARCHAR(100) NULL,
  "Payment_Reference" VARCHAR(100) NULL,
  "Payment_Amount" DECIMAL(15, 2) NULL,
  PRIMARY KEY ("Payment_id")
);

CREATE TABLE IF NOT EXISTS "Money" (
  "Money_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NOT NULL,
  "Stakeholder_id" INT NULL,
  "Asset_id" INT NULL,
  "Structures_id" INT NULL,
  "Product_id" INT NULL,
  "Income_id" INT NULL,
  "Payment_id" INT NULL,
  "Journal_id" INT NULL,
  "Transactions_id" INT NULL,
  "Settlement_transaction_id" INT NULL,
  "Cycle_id" INT NULL,
  "Instrument_type" VARCHAR(45) NULL,
  "Instrument_Class" VARCHAR(20) NULL,
  "Accounting_Treatment" VARCHAR(30) NULL,
  "Money_Status" VARCHAR(20) NOT NULL,
  "Repayment_Frequency" VARCHAR(10) NULL,
  "Risk_Level" VARCHAR(10) NULL,
  "Money_Name" VARCHAR(45) NULL,
  "Principal_amount" DECIMAL(15, 2) NULL,
  "Interest_rate" DECIMAL(10, 6) NULL,
  "Outstanding_Amount" DECIMAL(15, 2) NULL,
  "Start_date" TIMESTAMP NULL,
  "Maturity_date" TIMESTAMP NULL,
  "Due_Date" DATE NULL,
  "Risk_note" VARCHAR(255) NULL,
  PRIMARY KEY ("Money_id")
);

CREATE TABLE IF NOT EXISTS "Account_History" (
  "History_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NOT NULL,
  "Transaction_id" INT NOT NULL,
  "Old_Balance" DECIMAL(15, 2) NULL,
  "Debit" DECIMAL(15, 2) NULL,
  "Credit" DECIMAL(15, 2) NULL,
  "New_Balance" DECIMAL(15, 2) NULL,
  "Balance_Type" VARCHAR(45) NULL,
  "Reason" VARCHAR(255) NULL,
  "Entry_date" DATE NULL,
  "Created_at" TIMESTAMP NULL,
  "Author" INT NULL,
  "Approved_by" INT NULL,
  "Approval_date" TIMESTAMP NULL,
  "Previous_value" VARCHAR(255) NULL,
  "New_value" VARCHAR(255) NULL,
  "Trigger_rule" INT NULL,
  PRIMARY KEY ("History_id")
);

CREATE TABLE IF NOT EXISTS "Narrative" (
  "Narrative_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NULL,
  "Transaction_id" INT NULL,
  "Records_id" INT NULL,
  "Document_id" INT NULL,
  "Narrative_type" VARCHAR(45) NULL,
  "Narrative_audience" VARCHAR(15) NULL,
  "Is_Generated" INT NOT NULL DEFAULT 1,
  "Generated_from_catalogue" INT NULL,
  "Narrative_source" VARCHAR(20) NULL,
  "Description" TEXT NULL,
  "Language" VARCHAR(20) NULL,
  "Author" INT NULL,
  "Narrative_date" TIMESTAMP NULL,
  PRIMARY KEY ("Narrative_id")
);

CREATE TABLE IF NOT EXISTS "Knowledge" (
  "Knowledge_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Account_id" INT NULL,
  "Transactions_id" INT NULL,
  "Records_id" INT NULL,
  "Document_id" INT NULL,
  "Explanation" TEXT NULL,
  "Knowledge_type" VARCHAR(20) NULL,
  "Recommendation" TEXT NULL,
  "Lesson_Learned" TEXT NULL,
  "Decision_Reason" TEXT NULL,
  "Alternative_Considered" TEXT NULL,
  "Context" VARCHAR(45) NULL,
  "Confidence_Level" SMALLINT NULL,
  "Language" VARCHAR(20) NULL,
  "Audience" INT NULL,
  "Author" INT NULL,
  "Entry_date" DATE NULL,
  PRIMARY KEY ("Knowledge_id")
);

-- ==== Foreign key constraints (added after all tables exist) ====

ALTER TABLE "Product" ADD CONSTRAINT "fk_Product_fk_prod_stakeHolder_1" FOREIGN KEY ("Stakeholder_id") REFERENCES "Stakeholder" (
    "Stakeholder_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "LogicConditions" ADD CONSTRAINT "fk_LogicConditions_fk_lc_Account_1" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "LogicConditions" ADD CONSTRAINT "fk_LogicConditions_fk_lc_Structure_2" FOREIGN KEY ("Structure_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "LogicConditions" ADD CONSTRAINT "fk_LogicConditions_fk_lc_Logic_3" FOREIGN KEY ("Parent_Logic") REFERENCES "LogicConditions" (
    "LogicConditions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "LogicConditions" ADD CONSTRAINT "fk_LogicConditions_fk_lc_Catalogue_4" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Resources" ADD CONSTRAINT "fk_Resources_fk_res_Product_1" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Resources" ADD CONSTRAINT "fk_Resources_fk_res_Records_2" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Resources" ADD CONSTRAINT "fk_Resources_fk_res_Provider_3" FOREIGN KEY ("Stakeholder_id") REFERENCES "Stakeholder" (
    "Stakeholder_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Assets" ADD CONSTRAINT "fk_Assets_fk_Assets_Records_1" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Assets" ADD CONSTRAINT "fk_Assets_fk_Assets_Account_2" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Assets" ADD CONSTRAINT "fk_Assets_fk_Assets_Catalogue_3" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Equity" ADD CONSTRAINT "fk_Equity_fk_Equity_Records_1" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Equity" ADD CONSTRAINT "fk_Equity_fk_Equity_Account_2" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Equity" ADD CONSTRAINT "fk_Equity_fk_Equity_Catalogue_3" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Liability" ADD CONSTRAINT "fk_Liability_fk_Liability_Records_1" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Liability" ADD CONSTRAINT "fk_Liability_fk_Liability_Account_2" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Liability" ADD CONSTRAINT "fk_Liability_fk_Liability_Catalogue_3" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Income" ADD CONSTRAINT "fk_Income_fk_Income_Records_1" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Income" ADD CONSTRAINT "fk_Income_fk_Income_Account_2" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Income" ADD CONSTRAINT "fk_Income_fk_Income_Catalogue_3" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Income" ADD CONSTRAINT "fk_Income_fk_Income_Transaction_4" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Income" ADD CONSTRAINT "fk_Income_fk_Income_Period_5" FOREIGN KEY ("Period_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Expenditure" ADD CONSTRAINT "fk_Expenditure_fk_Expend_Records_1" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Expenditure" ADD CONSTRAINT "fk_Expenditure_fk_Expend_Account_2" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Expenditure" ADD CONSTRAINT "fk_Expenditure_fk_Expend_Catalogue_3" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Expenditure" ADD CONSTRAINT "fk_Expenditure_fk_Expend_Transxn_4" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Expenditure" ADD CONSTRAINT "fk_Expenditure_fk_Expend_Struct_5" FOREIGN KEY ("Period_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Transactions_1" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Account_2" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Catalogue_3" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Product_4" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Administration_5" FOREIGN KEY ("Administration_id") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Correction_6" FOREIGN KEY ("Correction_of") REFERENCES "Journal" (
    "Journal_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Period_7" FOREIGN KEY ("Period_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Journal" ADD CONSTRAINT "fk_Journal_fk_jnl_Corrected_By_8" FOREIGN KEY ("Corrected_By") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Reports" ADD CONSTRAINT "fk_Reports_fk_Rprt_Transaction_1" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Reports" ADD CONSTRAINT "fk_Reports_fk_Rprt_Records_2" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Reports" ADD CONSTRAINT "fk_Reports_fk_Rprt_Ledger_3" FOREIGN KEY ("Ledger_id") REFERENCES "Ledger" (
    "Ledger_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Reports" ADD CONSTRAINT "fk_Reports_fk_Rprt_Account_4" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Reports" ADD CONSTRAINT "fk_Reports_fk_Rprt_Journal_5" FOREIGN KEY ("Journal_id") REFERENCES "Journal" (
    "Journal_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Reports" ADD CONSTRAINT "fk_Reports_fk_Rprt_Parent_6" FOREIGN KEY ("Parent_Report_id") REFERENCES "Reports" (
    "Reports_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Assets_1" FOREIGN KEY ("Asset_id") REFERENCES "Assets" (
    "Assets_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Liability_2" FOREIGN KEY ("Liablity_id") REFERENCES "Liability" (
    "Liability_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Equity_3" FOREIGN KEY ("Equity_id") REFERENCES "Equity" (
    "Equity_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Income_4" FOREIGN KEY ("Income_id") REFERENCES "Income" (
    "Income_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Expenditure_5" FOREIGN KEY ("Expenditure_id") REFERENCES "Expenditure" (
    "Expenditure_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Accounts_6" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Journal_7" FOREIGN KEY ("Journal_id") REFERENCES "Journal" (
    "Journal_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Trxns_8" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Admin_9" FOREIGN KEY ("Administration_id") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Ledger" ADD CONSTRAINT "fk_Ledger_fk_Ldgr_Prnt_Rprt_10" FOREIGN KEY ("Parent_Report_id") REFERENCES "Reports" (
    "Reports_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Account_1" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Resrcs_2" FOREIGN KEY ("Resources_id") REFERENCES "Resources" (
    "Resources_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Assets_3" FOREIGN KEY ("Asset_id") REFERENCES "Assets" (
    "Assets_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Equity_4" FOREIGN KEY ("Equity_id") REFERENCES "Equity" (
    "Equity_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Prdct_5" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Catlge_6" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Ledger_7" FOREIGN KEY ("Ledger_id") REFERENCES "Ledger" (
    "Ledger_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Trxn_8" FOREIGN KEY ("Transaction_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Organisation" ADD CONSTRAINT "fk_Organisation_fk_Orgsn_Mngmnt_9" FOREIGN KEY ("Administration_id") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Records" ADD CONSTRAINT "fk_Records_fk_Recrd_Catlge_1" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Records" ADD CONSTRAINT "fk_Records_fk_Recrd_Transxn_2" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Records" ADD CONSTRAINT "fk_Records_fk_Recrd_Admin_3" FOREIGN KEY ("Administration_id") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Records" ADD CONSTRAINT "fk_Records_fk_Recrd_Organstn_4" FOREIGN KEY ("Entreprise_id") REFERENCES "Organisation" (
    "Entreprise_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Records" ADD CONSTRAINT "fk_Records_fk_Recrd_Struct_5" FOREIGN KEY ("Structures_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Records" ADD CONSTRAINT "fk_Records_fk_Recrd_Period_6" FOREIGN KEY ("Period_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Stkhldr_1" FOREIGN KEY ("Stakeholder_id") REFERENCES "Stakeholder" (
    "Stakeholder_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Reprt_2" FOREIGN KEY ("Reports_id") REFERENCES "Reports" (
    "Reports_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Chngd_by_3" FOREIGN KEY ("Modified_by") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Cycle_4" FOREIGN KEY ("Cycle_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Gnrtd_By_5" FOREIGN KEY ("Generated_By") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Apprvd_By_6" FOREIGN KEY ("Approved_By") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Transxn_7" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Documents" ADD CONSTRAINT "fk_Documents_fk_Doc_Orgsntn_8" FOREIGN KEY ("Organisation_id") REFERENCES "Organisation" (
    "Entreprise_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mgmt_Catlge_1" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mgmt_Logic_2" FOREIGN KEY ("LogicConditons_id") REFERENCES "LogicConditions" (
    "LogicConditions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mgmt_Prcss_3" FOREIGN KEY ("ProcessActions_id") REFERENCES "ProcessActions" (
    "ProcessActions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mgmt_Stkhlder_4" FOREIGN KEY ("Stakeholder_id") REFERENCES "Stakeholder" (
    "Stakeholder_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mgmt_Prdct_5" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mgmt_Rcrds_6" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mgmt_Orgstn_7" FOREIGN KEY ("Organisation_id") REFERENCES "Organisation" (
    "Entreprise_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Management" ADD CONSTRAINT "fk_Management_fk_Mngmt_Doc_8" FOREIGN KEY ("Document_id") REFERENCES "Documents" (
    "Document_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Structures" ADD CONSTRAINT "fk_Structures_fk_Struct_Account_1" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Structures" ADD CONSTRAINT "fk_Structures_fk_Struct_CreatedBy_2" FOREIGN KEY ("Created_By") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Structures" ADD CONSTRAINT "fk_Structures_fk_Struct_ApprovedBy_3" FOREIGN KEY ("Approved_By") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Structures" ADD CONSTRAINT "fk_Structures_fk_Struct_Parent_4" FOREIGN KEY ("Parent_Structure_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account_codes" ADD CONSTRAINT "fk_Account_codes_fk_Parent_code_1" FOREIGN KEY ("Parent_code_id") REFERENCES "Account_codes" (
    "Account_codes_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_Catlog_Struct_1" FOREIGN KEY ("Structures_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_Catlog_Logic_2" FOREIGN KEY ("LogicConditons_id") REFERENCES "LogicConditions" (
    "LogicConditions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_Catlog_Action_3" FOREIGN KEY ("ProcessActions_id") REFERENCES "ProcessActions" (
    "ProcessActions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_Catlog_PrimLgc_4" FOREIGN KEY ("Primary_Logic_id") REFERENCES "LogicConditions" (
    "LogicConditions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_cat_debit_acct_5" FOREIGN KEY ("Debit_Account_fk_id") REFERENCES "Account_codes" (
    "Account_codes_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_cat_credit_acct_6" FOREIGN KEY ("Credit_Account_fk_id") REFERENCES "Account_codes" (
    "Account_codes_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_cat_sec_debit_7" FOREIGN KEY ("Secondary_Debit_fk_id") REFERENCES "Account_codes" (
    "Account_codes_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Catalogue" ADD CONSTRAINT "fk_Catalogue_fk_cat_sec_credit_8" FOREIGN KEY ("Secondary_Credit_fk_id") REFERENCES "Account_codes" (
    "Account_codes_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account" ADD CONSTRAINT "fk_Account_fk_Accnt_Stkhldr_1" FOREIGN KEY ("Stakeholder_id") REFERENCES "Stakeholder" (
    "Stakeholder_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account" ADD CONSTRAINT "fk_Account_fk_Accnt_Prdct_2" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account" ADD CONSTRAINT "fk_Account_fk_Accnt_Catlge_3" FOREIGN KEY ("Catalogue_id") REFERENCES "Catalogue" (
    "Catalogue_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account" ADD CONSTRAINT "fk_Account_fk_Accnt_Recrd_4" FOREIGN KEY ("Origin_Record_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account" ADD CONSTRAINT "fk_Account_fk_Accnt_Acc_Code_5" FOREIGN KEY ("Account_Code_id") REFERENCES "Account_codes" (
    "Account_codes_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Evidence" ADD CONSTRAINT "fk_Evidence_fk_Evidns_Docs_1" FOREIGN KEY ("Document_id") REFERENCES "Documents" (
    "Document_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Evidence" ADD CONSTRAINT "fk_Evidence_fk_Evidns_Mgmnt_2" FOREIGN KEY ("Verified_by") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Evidence" ADD CONSTRAINT "fk_Evidence_fk_Evidns_Account_3" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Evidence" ADD CONSTRAINT "fk_Evidence_fk_Evidns_Transxn_4" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Evidence" ADD CONSTRAINT "fk_Evidence_fk_Evidns_Recrd_5" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Product_1" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Process_2" FOREIGN KEY ("ProcessActions_id") REFERENCES "ProcessActions" (
    "ProcessActions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Account_3" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Correction_4" FOREIGN KEY ("Correction_of") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Cycle_5" FOREIGN KEY ("Cycle_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Parent_6" FOREIGN KEY ("Cycle_parent") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Evidence_7" FOREIGN KEY ("Evidence_id") REFERENCES "Evidence" (
    "Evidence_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Records_8" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Transactions" ADD CONSTRAINT "fk_Transactions_fk_txn_Corrected_By_9" FOREIGN KEY ("Corrected_By") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Payment" ADD CONSTRAINT "fk_Payment_fk_pay_Product_1" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Payment" ADD CONSTRAINT "fk_Payment_fk_pay_Records_2" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Payment" ADD CONSTRAINT "fk_Payment_fk_pay_Money_3" FOREIGN KEY ("Money_id") REFERENCES "Money" (
    "Money_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Paymnt_1" FOREIGN KEY ("Payment_id") REFERENCES "Payment" (
    "Payment_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Transxn_2" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Accnt_3" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Assets_4" FOREIGN KEY ("Asset_id") REFERENCES "Assets" (
    "Assets_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Incom_5" FOREIGN KEY ("Income_id") REFERENCES "Income" (
    "Income_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Struct_6" FOREIGN KEY ("Structures_id") REFERENCES "Structures" (
    "Structures_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Prdct_7" FOREIGN KEY ("Product_id") REFERENCES "Product" (
    "Product_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Jrnl_8" FOREIGN KEY ("Journal_id") REFERENCES "Journal" (
    "Journal_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Stkhldr_9" FOREIGN KEY ("Stakeholder_id") REFERENCES "Stakeholder" (
    "Stakeholder_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Cycle_10" FOREIGN KEY ("Cycle_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "Money" ADD CONSTRAINT "fk_Money_fk_Mony_Setlmt_transxn_11" FOREIGN KEY ("Settlement_transaction_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account_History" ADD CONSTRAINT "fk_Account_History_fk_Acc_His_Accounts_1" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account_History" ADD CONSTRAINT "fk_Account_History_fk_Acc_His_Transxn_2" FOREIGN KEY ("Transaction_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account_History" ADD CONSTRAINT "fk_Account_History_fk_Acc_His_Author_3" FOREIGN KEY ("Author") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account_History" ADD CONSTRAINT "fk_Account_History_fk_Acc_His_Apprvr_4" FOREIGN KEY ("Approved_by") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Account_History" ADD CONSTRAINT "fk_Account_History_fk_Acc_His_TrigRule_5" FOREIGN KEY ("Trigger_rule") REFERENCES "LogicConditions" (
    "LogicConditions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Narrative" ADD CONSTRAINT "fk_Narrative_fk_Nartiv_Accnt_1" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Narrative" ADD CONSTRAINT "fk_Narrative_fk_Nartiv_Docs_2" FOREIGN KEY ("Document_id") REFERENCES "Documents" (
    "Document_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Narrative" ADD CONSTRAINT "fk_Narrative_fk_Nartiv_Stkhldrs_3" FOREIGN KEY ("Author") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Narrative" ADD CONSTRAINT "fk_Narrative_fk_Nartiv_Transxn_4" FOREIGN KEY ("Transaction_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Narrative" ADD CONSTRAINT "fk_Narrative_fk_Nartiv_Recrd_5" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Knowledge" ADD CONSTRAINT "fk_Knowledge_fk_Knwldg_Accnts_1" FOREIGN KEY ("Account_id") REFERENCES "Account" (
    "Account_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Knowledge" ADD CONSTRAINT "fk_Knowledge_fk_Knwldg_Docs_2" FOREIGN KEY ("Document_id") REFERENCES "Documents" (
    "Document_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Knowledge" ADD CONSTRAINT "fk_Knowledge_fk_Knwldg_Mngnt_3" FOREIGN KEY ("Audience") REFERENCES "Management" (
    "Administration_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Knowledge" ADD CONSTRAINT "fk_Knowledge_fk_Knwldg_Stkhldr_4" FOREIGN KEY ("Author") REFERENCES "Stakeholder" (
    "Stakeholder_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Knowledge" ADD CONSTRAINT "fk_Knowledge_fk_Knwldg_Transxs_5" FOREIGN KEY ("Transactions_id") REFERENCES "Transactions" (
    "Transactions_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE "Knowledge" ADD CONSTRAINT "fk_Knowledge_fk_Knwldg_Rcrd_6" FOREIGN KEY ("Records_id") REFERENCES "Records" (
    "Records_id"
  ) ON DELETE NO ACTION ON UPDATE NO ACTION;

-- ==== Indexes ====

CREATE INDEX "fk_StakeHolder_idx_Product" ON "Product" ("Stakeholder_id");
CREATE INDEX "fk_Logic_idx_LogicConditions" ON "LogicConditions" ("Parent_Logic");
CREATE INDEX "fk_Structure_idx_LogicConditions" ON "LogicConditions" ("Structure_id");
CREATE INDEX "fk_Account_idx_LogicConditions" ON "LogicConditions" ("Account_id");
CREATE INDEX "fk_Catalogue_idx_LogicConditions" ON "LogicConditions" ("Catalogue_id");
CREATE INDEX "fk_Product_idx_Resources" ON "Resources" ("Product_id");
CREATE INDEX "fk_Records_idx_Resources" ON "Resources" ("Records_id");
CREATE INDEX "fk_Provider_idx_Resources" ON "Resources" ("Stakeholder_id");
CREATE INDEX "fk_Records_idx_Assets" ON "Assets" ("Records_id");
CREATE INDEX "fk_Account_idx_Assets" ON "Assets" ("Account_id");
CREATE INDEX "fk_Catalogue_idx_Assets" ON "Assets" ("Catalogue_id");
CREATE INDEX "fk_Records_idx_Equity" ON "Equity" ("Records_id");
CREATE INDEX "fk_Account_idx_Equity" ON "Equity" ("Account_id");
CREATE INDEX "fk_Catalogue_idx_Equity" ON "Equity" ("Catalogue_id");
CREATE INDEX "fk_Records_idx_Liability" ON "Liability" ("Records_id");
CREATE INDEX "fk_Account_idx_Liability" ON "Liability" ("Account_id");
CREATE INDEX "fk_Catalogue_idx_Liability" ON "Liability" ("Catalogue_id");
CREATE INDEX "fk_Records_idx_Income" ON "Income" ("Records_id");
CREATE INDEX "fk_Account_idx_Income" ON "Income" ("Account_id");
CREATE INDEX "fk_Catalogue_idx_Income" ON "Income" ("Catalogue_id");
CREATE INDEX "fk_Transaction_idx_Income" ON "Income" ("Transactions_id");
CREATE INDEX "idx_income_unit_Income" ON "Income" ("Business_Unit");
CREATE INDEX "idx_income_period_Income" ON "Income" ("Period", "Period_end");
CREATE INDEX "fk_Income_Period_idx_Income" ON "Income" ("Period_id");
CREATE INDEX "fk_Records_idx_Expenditure" ON "Expenditure" ("Records_id");
CREATE INDEX "fk_Account_idx_Expenditure" ON "Expenditure" ("Account_id");
CREATE INDEX "fk_Catalogue_idx_Expenditure" ON "Expenditure" ("Catalogue_id");
CREATE INDEX "idx_exp_period_Expenditure" ON "Expenditure" ("Period", "Period_end");
CREATE INDEX "idx_exp_unit_Expenditure" ON "Expenditure" ("Business_Unit");
CREATE INDEX "fk_Expend_Struct_idx_Expenditure" ON "Expenditure" ("Period_id");
CREATE INDEX "fk_Transactions_idx_Journal" ON "Journal" ("Transactions_id");
CREATE INDEX "fk_Account_idx_Journal" ON "Journal" ("Account_id");
CREATE INDEX "fk_Catalogue_idx_Journal" ON "Journal" ("Catalogue_id");
CREATE INDEX "fk_Product_idx_Journal" ON "Journal" ("Product_id");
CREATE INDEX "fk_Administration_idx_Journal" ON "Journal" ("Administration_id");
CREATE INDEX "fk_Correction_idx_Journal" ON "Journal" ("Correction_of");
CREATE INDEX "idx_journal_date_Journal" ON "Journal" ("Created_at");
CREATE INDEX "idx_journal_basis_Journal" ON "Journal" ("Recognition_Basis");
CREATE INDEX "idx_journal_account_date_Journal" ON "Journal" ("Account_id", "Created_at");
CREATE INDEX "fk_Period_idx_Journal" ON "Journal" ("Period_id");
CREATE INDEX "idx_journal_txn_date_Journal" ON "Journal" ("Transaction_Date");
CREATE INDEX "idx_journal_account_period_Journal" ON "Journal" ("Account_id", "Period_id");
CREATE INDEX "fk_Corrected_By_idx_Journal" ON "Journal" ("Corrected_By");
CREATE INDEX "idx_correction_status_Journal" ON "Journal" ("Correction_Status");
CREATE INDEX "fk_Transaction_idx_Reports" ON "Reports" ("Transactions_id");
CREATE INDEX "fk_Records_idx_Reports" ON "Reports" ("Records_id");
CREATE INDEX "fk_Ledger_idx_Reports" ON "Reports" ("Ledger_id");
CREATE INDEX "fk_Account_idx_Reports" ON "Reports" ("Account_id");
CREATE INDEX "fk_Journal_idx_Reports" ON "Reports" ("Journal_id");
CREATE INDEX "fk_Parent_idx_Reports" ON "Reports" ("Parent_Report_id");
CREATE INDEX "fk_Liability_idx_Ledger" ON "Ledger" ("Liablity_id");
CREATE INDEX "fk_Equity_idx_Ledger" ON "Ledger" ("Equity_id");
CREATE INDEX "fk_Income_idx_Ledger" ON "Ledger" ("Income_id");
CREATE INDEX "fk_Expenditure_idx_Ledger" ON "Ledger" ("Expenditure_id");
CREATE INDEX "fk_Assets_idx_Ledger" ON "Ledger" ("Asset_id");
CREATE INDEX "fk_Tranactions_idx_Ledger" ON "Ledger" ("Transactions_id");
CREATE INDEX "fk_Journal_idx_Ledger" ON "Ledger" ("Journal_id");
CREATE INDEX "fk_Administration_idx_Ledger" ON "Ledger" ("Administration_id");
CREATE INDEX "idx_report_stage_Ledger" ON "Ledger" ("Report_Stage");
CREATE INDEX "fk_Parent_Report_idx_Ledger" ON "Ledger" ("Parent_Report_id");
CREATE INDEX "fk_Account_idx_Organisation" ON "Organisation" ("Account_id");
CREATE INDEX "fk_Product_idx_Organisation" ON "Organisation" ("Product_id");
CREATE INDEX "fk_Equity_idx_Organisation" ON "Organisation" ("Equity_id");
CREATE INDEX "fk_Assets_idx_Organisation" ON "Organisation" ("Asset_id");
CREATE INDEX "fk_Catalogue_idx_Organisation" ON "Organisation" ("Catalogue_id");
CREATE INDEX "fk_Ledger_idx_Organisation" ON "Organisation" ("Ledger_id");
CREATE INDEX "fk_Transaction_idx_Organisation" ON "Organisation" ("Transaction_id");
CREATE INDEX "fk_Management_idx_Organisation" ON "Organisation" ("Administration_id");
CREATE INDEX "fk_Resources_idx_Organisation" ON "Organisation" ("Resources_id");
CREATE INDEX "fk_Transaction_idx_Records" ON "Records" ("Transactions_id");
CREATE INDEX "fk_Catalogue_idx_Records" ON "Records" ("Catalogue_id");
CREATE INDEX "fk_Administration_idx_Records" ON "Records" ("Administration_id");
CREATE INDEX "fk_Organisation_idx_Records" ON "Records" ("Entreprise_id");
CREATE INDEX "fk_Structures_idx_Records" ON "Records" ("Structures_id");
CREATE INDEX "idx_records_date_Records" ON "Records" ("Records_date");
CREATE INDEX "idx_records_type_Records" ON "Records" ("Records_type");
CREATE INDEX "idx_records_unit_Records" ON "Records" ("Business_Unit");
CREATE INDEX "fk_Period_idx_Records" ON "Records" ("Period_id");
CREATE INDEX "fk_Stakeholder_idx_Documents" ON "Documents" ("Stakeholder_id");
CREATE INDEX "fk_Report_idx_Documents" ON "Documents" ("Reports_id");
CREATE INDEX "fk_Changed_by_idx_Documents" ON "Documents" ("Modified_by");
CREATE INDEX "fk_Approved_By_idx_Documents" ON "Documents" ("Approved_By");
CREATE INDEX "fk_Transactions_idx_Documents" ON "Documents" ("Transactions_id");
CREATE INDEX "fk_Doc_Orgsntn_idx_Documents" ON "Documents" ("Organisation_id");
CREATE UNIQUE INDEX "uq_doc_number_Documents" ON "Documents" ("Document_type", "Documents_no", "Organisation_id");
CREATE INDEX "fk_Catalogue_idx_Management" ON "Management" ("Catalogue_id");
CREATE INDEX "fk_Process_idx_Management" ON "Management" ("ProcessActions_id");
CREATE INDEX "fk_Logic_idx_Management" ON "Management" ("LogicConditons_id");
CREATE INDEX "fk_Stakeholder_idx_Management" ON "Management" ("Stakeholder_id");
CREATE INDEX "fk_Product_idx_Management" ON "Management" ("Product_id");
CREATE INDEX "fk_Records_idx_Management" ON "Management" ("Records_id");
CREATE INDEX "fk_Mngmt_Doc_idx_Management" ON "Management" ("Document_id");
CREATE INDEX "fk_Account_idx_Structures" ON "Structures" ("Account_id");
CREATE INDEX "fk_Parent_idx_Structures" ON "Structures" ("Parent_Structure_id");
CREATE INDEX "fk_Parent_code_idx_Account_codes" ON "Account_codes" ("Parent_code_id");
CREATE INDEX "uq_account_code_Account_codes" ON "Account_codes" ("Code");
CREATE INDEX "fk_Structures_idx_Catalogue" ON "Catalogue" ("Structures_id");
CREATE INDEX "fk_Logic_idx_Catalogue" ON "Catalogue" ("LogicConditons_id");
CREATE INDEX "fk_Action_idx_Catalogue" ON "Catalogue" ("ProcessActions_id");
CREATE INDEX "fk_PrimaryLogic_idx_Catalogue" ON "Catalogue" ("Primary_Logic_id");
CREATE INDEX "idx_catalogue_active_Catalogue" ON "Catalogue" ("Is_Active");
CREATE INDEX "fk_cat_debit_acct_idx_Catalogue" ON "Catalogue" ("Debit_Account_fk_id");
CREATE INDEX "fk_cat_credit_acct_idx_Catalogue" ON "Catalogue" ("Credit_Account_fk_id");
CREATE INDEX "fk_cat_sec_debit_idx_Catalogue" ON "Catalogue" ("Secondary_Debit_fk_id");
CREATE INDEX "fk_cat_sec_credit_idx_Catalogue" ON "Catalogue" ("Secondary_Credit_fk_id");
CREATE INDEX "fk_Product_idx_Account" ON "Account" ("Product_id");
CREATE INDEX "fk_Stakeholder_idx_Account" ON "Account" ("Stakeholder_id");
CREATE INDEX "fk_Catalogue_idx_Account" ON "Account" ("Catalogue_id");
CREATE INDEX "fk_Records_idx_Account" ON "Account" ("Origin_Record_id");
CREATE INDEX "fk_Account_Code_idx_Account" ON "Account" ("Account_Code_id");
CREATE INDEX "fk_Documents_idx_Evidence" ON "Evidence" ("Document_id");
CREATE INDEX "fk_Management_idx_Evidence" ON "Evidence" ("Verified_by");
CREATE INDEX "fk_Records_idx_Evidence" ON "Evidence" ("Records_id");
CREATE INDEX "fk_Transaction_idx_Evidence" ON "Evidence" ("Transactions_id");
CREATE INDEX "fk_Account_idx_Evidence" ON "Evidence" ("Account_id");
CREATE INDEX "fk_Product_idx_Transactions" ON "Transactions" ("Product_id");
CREATE INDEX "fk_Account_idx_Transactions" ON "Transactions" ("Account_id");
CREATE INDEX "fk_Correction_idx_Transactions" ON "Transactions" ("Correction_of");
CREATE INDEX "idx_Cycle_Transactions" ON "Transactions" ("Cycle_id");
CREATE INDEX "fk_Parent_idx_Transactions" ON "Transactions" ("Cycle_parent");
CREATE INDEX "idx_txn_cycle_status_Transactions" ON "Transactions" ("Cycle_status");
CREATE INDEX "idx_txn_cycle_type_Transactions" ON "Transactions" ("Cycle_type");
CREATE INDEX "fk_Evidence_idx_Transactions" ON "Transactions" ("Evidence_id");
CREATE INDEX "idx_txn_date_Transactions" ON "Transactions" ("Transactions_date");
CREATE INDEX "idx_txn_unit_Transactions" ON "Transactions" ("Business_Unit");
CREATE INDEX "idx_txn_date_unit_Transactions" ON "Transactions" ("Transactions_date", "Business_Unit");
CREATE INDEX "fk_Records_idx_Transactions" ON "Transactions" ("Records_id");
CREATE INDEX "fk_Corrected_By_idx_Transactions" ON "Transactions" ("Corrected_By");
CREATE INDEX "idx_correction_status_txn_Transactions" ON "Transactions" ("Cycle_status");
CREATE INDEX "fk_Product_idx_Payment" ON "Payment" ("Product_id");
CREATE INDEX "fk_Records_idx_Payment" ON "Payment" ("Records_id");
CREATE INDEX "fk_pay_Money_idx_Payment" ON "Payment" ("Money_id");
CREATE INDEX "fk_Cost_idx_Money" ON "Money" ("Payment_id");
CREATE INDEX "fk_Transaction_idx_Money" ON "Money" ("Transactions_id");
CREATE INDEX "fk_Account_idx_Money" ON "Money" ("Account_id");
CREATE INDEX "fk_Assets_idx_Money" ON "Money" ("Asset_id");
CREATE INDEX "fk_Revenue_idx_Money" ON "Money" ("Income_id");
CREATE INDEX "fk_Structures_idx_Money" ON "Money" ("Structures_id");
CREATE INDEX "fk_Product_idx_Money" ON "Money" ("Product_id");
CREATE INDEX "fk_Journal_idx_Money" ON "Money" ("Journal_id");
CREATE INDEX "fk_Stakeholder_idx_Money" ON "Money" ("Stakeholder_id");
CREATE INDEX "fk_Settlement_transaction_idx_Money" ON "Money" ("Settlement_transaction_id");
CREATE INDEX "fk_Transactions_idx_Account_History" ON "Account_History" ("Transaction_id");
CREATE INDEX "fk_Accounts_idx_Account_History" ON "Account_History" ("Account_id");
CREATE INDEX "fk_Approver_idx_Account_History" ON "Account_History" ("Approved_by");
CREATE INDEX "fk_Author_idx_Account_History" ON "Account_History" ("Author");
CREATE INDEX "fk_TriggerRule_idx_Account_History" ON "Account_History" ("Trigger_rule");
CREATE INDEX "fk_Documents_idx_Narrative" ON "Narrative" ("Document_id");
CREATE INDEX "fk_Stakeholders_idx_Narrative" ON "Narrative" ("Author");
CREATE INDEX "fk_Account_idx_Narrative" ON "Narrative" ("Account_id");
CREATE INDEX "fk_Nartiv_Transxn_Narrative" ON "Narrative" ("Transaction_id");
CREATE INDEX "fk_Nartiv_Recrd_Narrative" ON "Narrative" ("Records_id");
CREATE INDEX "fk_Documents_idx_Knowledge" ON "Knowledge" ("Document_id");
CREATE INDEX "fk_Records_idx_Knowledge" ON "Knowledge" ("Records_id");
CREATE INDEX "fk_Transactions_idx_Knowledge" ON "Knowledge" ("Transactions_id");
CREATE INDEX "fk_Management_idx_Knowledge" ON "Knowledge" ("Audience");
CREATE INDEX "fk_Stakeholder_idx_Knowledge" ON "Knowledge" ("Author");
CREATE INDEX "fk_Accounts_idx_Knowledge" ON "Knowledge" ("Account_id");
