-- Settings table: proper typed configuration system
-- Replaces the Preference_key/Preference_value pattern on Structures
CREATE TABLE IF NOT EXISTS "Settings" (
  "Setting_id" INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "Entreprise_id" INT NULL,
  "Setting_Category" VARCHAR(45) NOT NULL DEFAULT 'OTHER',
  "Setting_Name" VARCHAR(100) NOT NULL,
  "Setting_Value" VARCHAR(255) NOT NULL,
  "Data_Type" VARCHAR(10) NOT NULL DEFAULT 'STRING' CHECK ("Data_Type" IN ('STRING', 'DECIMAL', 'INT', 'BOOLEAN')),
  "Description" VARCHAR(255) NULL,
  "Effective_From" DATE NULL,
  "Effective_To" DATE NULL,
  "Created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("Setting_id")
);
CREATE INDEX IF NOT EXISTS "idx_settings_enterprise" ON "Settings" ("Entreprise_id");
CREATE INDEX IF NOT EXISTS "idx_settings_category" ON "Settings" ("Setting_Category");

-- Succession fields on Management table
ALTER TABLE "Management" ADD COLUMN IF NOT EXISTS "Succession_Role" VARCHAR(20) NULL;
ALTER TABLE "Management" ADD COLUMN IF NOT EXISTS "Lifecycle_Status" VARCHAR(20) NULL;
ALTER TABLE "Management" ADD COLUMN IF NOT EXISTS "Succession_Status" VARCHAR(20) NULL;
ALTER TABLE "Management" ADD COLUMN IF NOT EXISTS "Legal_Verification" VARCHAR(20) NULL DEFAULT 'NOT_VERIFIED';
ALTER TABLE "Management" ADD COLUMN IF NOT EXISTS "Succession_Date" DATE NULL;
ALTER TABLE "Management" ADD COLUMN IF NOT EXISTS "Succession_Notes" TEXT NULL;
